### ISSUE TITLE
melhorar build e publicação de bibliotecas utilizando lerna

### ISSUE THREAD

**Issue by igr-santos** [nossas/bonde#1041]
- entender o mecanismo de publicação do lerna
- fazer build e publicações em staging
- fazer build e publicações em produção

**Comment by lpirola** [comment]
@igr-santos vale adicionar no drone comandos para publicação automática no npm.

Podemos usar como exemplo o slate-editor! https://github.com/nossas/slate-editor/blob/develop/.drone.yml#L10

**Comment by alalbux** [comment]
achei maneiro esse artigo, acho que tem uns pensamentos legais pra aplicar nessa task aqui https://doppelmutzi.github.io/monorepo-lerna-yarn-workspaces/

**Comment by lpirola** [comment]
muito bom @alalbux, será muito útil para resolvermos a  #1097
