### ISSUE TITLE
Turn on in custom domain redirect url from non-www to www

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#105]
enforce support to www and non-www url to any mobilization when configured customized domains

**Comment by gabrielrtakeda** [comment]
Forgot to reference issue on commits.

The list of commits are:
- https://github.com/ourcities/hub-client/commit/7b55581608d850e158809390e7b4fb845aea00a4 Remove www. from host param to compare with customized domain.
- https://github.com/ourcities/hub-client/commit/d19c8476b1dfc35c6de17d8c4ea7f55cdb4791d6 Redirect non-www mobilization domain to www with 301 status code.

**Comment by lpirola** [comment]
Maybe, we need to check what domain is set as default with www or withou and then make redirect, what do you think?

**Comment by gabrielrtakeda** [comment]
You mean then it would be better to create something more flexible so that it is more easy to set the redirect with www or without www?

How can we check if the default is with www ou without www?
From mob config?

**Comment by lpirola** [comment]
Yep, from mob config in domain settings

**Comment by lpirola** [comment]
While I was thinking on how solve this redirect without making a  round trip to API, I found the following solution:

we create a file, which will live in our version system with a list of all domains we can't redirect. 

When a user visit any URL,  we open that file and check if domain exist in the list and redirect to www or not. What do you think?

Maybe this list of domains can accept regular expressions.

**Comment by gabrielrtakeda** [comment]
I think this way is the best solution for now. The only question that i am is how this list is updated. At what moment we set a new domain that we cannot redirect to www for example..

**Comment by gabrielrtakeda** [comment]
We should check if the mobilization domain isn't setted with `www`, and then, we add this domain to that list?

For example, if the mobilization's domain setting is setted like this:
<img width="385" alt="screen shot 2016-07-18 at 12 44 39" src="https://cloud.githubusercontent.com/assets/5435389/16920804/840125cc-4ce5-11e6-98a5-728c9ab7de3b.png">

We should get this domain and add to the end of that file and, if the mobilization's domain is setted like this:
<img width="414" alt="screen shot 2016-07-18 at 12 46 26" src="https://cloud.githubusercontent.com/assets/5435389/16920847/abf1b8d0-4ce5-11e6-8b28-6d9d61efc241.png">

We just leave it to redirect to www if user access the mobilization's url without www?

**Comment by lpirola** [comment]
This list is only updated when we add this domain to this file manually.

**Comment by gabrielrtakeda** [comment]
Ok, i'll do that way 😉

**Comment by gabrielrtakeda** [comment]
## Redirect "Blacklist"

```
2016.meurio.org.br
apoie.minhasampa.org.br
boletim.defezap.org.br
boletim01.defezap.org.br
boletim02.defezap.org.br
boletim03.defezap.org.br
boletim04.defezap.org.br
boletim05.defezap.org.br
boletim06.defezap.org.br
boletim07.defezap.org.br
boletim08.defezap.org.br
boletim09.defezap.org.br
boletim10.defezap.org.br
boletim11.defezap.org.br
boletim12.defezap.org.br
cpidoaborto.meurio.org.br
deguardapelasescolas.minhasampa.org.br
encontrodacidadania.minhacampinas.org.br
mulheresmobilizadas.minhasampa.org.br
parqueaugusta.minhasampa.org.br
paulistaaberta.minhasampa.org.br
protestonaoecrime.minhasampa.org.br
saibamais.defezap.org.br
todoscomosestudantes.minhasampa.org.br
viradaocupacao.minhasampa.org.br
```

The `boletim.defezap.org.br` and its variations i'll do a regex like `boletim\d*.defezap.org.br`

**Comment by gabrielrtakeda** [comment]
The mobilizations with custom domain wich is not included in blacklist mobilizations domain is redirecting with `www` but, is not accessing the content of the page. It occurs an error and the mobilization isn't accessing. Need to revert the merge to master.

**Comment by gabrielrtakeda** [comment]
The cause of the error was identified. In the line https://github.com/ourcities/hub-client/commit/856f160d59bcdabd937b158221acd11e314bac88#diff-68b465296fc22e547ca452eec506a12dR25, it cannot remove the `www`. If we have the blacklist of mobilizations that cannot redirect to `www.`, then we do not need to verify that. Once that the only blacklisted mobilizations are cannot redirect to `www.`.

**Comment by gabrielrtakeda** [comment]
Is need to modify api mobilizations endpoint `where` condition to verify `slug` and `custom_domain` fields with `www` ou without. Code example:
```ruby
@mobilizations.where('custom_domain = ? or custom_domain = ?', "www.#{params['custom_domain']}", params['custom_domain']) if params[:custom_domain].present?
@mobilizations.where('slug = ? or slug = ?', "www.#{params['slug']}", params['slug']) if params[:slug].present?
```
