### ISSUE TITLE
[ admin-canary ] Mobile UI home

### ISSUE THREAD

**Issue by alalbux** [nossas/bonde#1056]
### Contexto

Alguns componentes como o header e o footer não ficam acessiveis os links comuns da página.

### Exemplo

![Captura de Tela 2019-05-07 às 11 18 08](https://user-images.githubusercontent.com/38147979/57310318-f3089080-70bf-11e9-8bcf-1f76e5f02df0.png)
![Captura de Tela 2019-05-07 às 11 18 17](https://user-images.githubusercontent.com/38147979/57310319-f3089080-70bf-11e9-9753-4aaf89a54a2b.png)

### Descrição técnica

```
TODO - Sugestão de interface
```

### Requisitos e Critérios de Aceite

- [ ]

**Comment by lpirola** [comment]
resolvido com a migração para o bonde-components
