### ISSUE TITLE
[beta][admin-canary] Implementar navegação para fluxo de chatbot

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#1059]
### Contexto
Para darmos continuidad no desenvolvimento do `admin-canary` precisamos criar a navegação entre os subniveis de navegação do bonde.

### Exemplo
![Captura de Tela 2019-05-14 às 13 19 11](https://user-images.githubusercontent.com/38147979/57714490-029d5180-764b-11e9-8d0b-236fd8ed4397.png)
![Captura de Tela 2019-05-14 às 13 19 21](https://user-images.githubusercontent.com/38147979/57714491-029d5180-764b-11e9-844a-d05e2f7096ff.png)
![Captura de Tela 2019-05-14 às 13 19 34](https://user-images.githubusercontent.com/38147979/57714492-029d5180-764b-11e9-91c9-1fde2275c68c.png)

### Requisitos e Critérios de Aceite

- [ ] Menu dropdrown com navegação entre comunidades
- [ ] Submenu com navegação entre configurações de comunidade

Definição de entregue:
- [ ] Página de chatbot com navegação acessível

**Comment by alalbux** [comment]
Será necessário um ajuste no componente de listagem das communidades na home para enquadrarem com o desenho que a Talita desenho.

Será necessário remover o estilo de botão e colocar uma opacidade no ícone quando selecionado

Ex:
![Captura de Tela 2019-07-26 às 17 53 21](https://user-images.githubusercontent.com/38147979/61980884-638fc100-afce-11e9-90a1-7313a582a898.png)

**Comment by alalbux** [comment]
Com o desmembramento da `feature/chatbot`, será necessario aguardar entrar os ajustes dentro do `feature/bonde-diagram`
