### ISSUE TITLE
TypeError: Cannot read property 'email' of undefined

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#1071]
https://sentry.io/organizations/nossas/issues/1035312783/?referrer=github_plugin

```
TypeError: Cannot read property 'email' of undefined
  at c (components/navigation/sidebar/sidebar.js:139:43)
  at None (mobrender/redux/action-creators/async-fetch-mobilizations.js:16:9)
...
(16 additional frame(s) were not displayed)
```

**Comment by rolivegab** [comment]
O bug acontece quando você tenta acessar a tela de mobilizations do app.bonde enquanto está autenticado através da api-v3.
Quando o processo de autenticação é feito através da api-v2, tudo funciona como deveria.

**Comment by rolivegab** [comment]
Partindo do princípio de que não é possível utilizar as duas apis (a v2 e a v3) ao mesmo tempo, não faz sentido converter o app.bonde para funcionar com a v3, pois ele é um sistema antigo e está para ser substituído pelo admin-canary.

A melhor solução para resolver o bug é continuar a desenvolver as telas do admin-canary e deixar a api-v2 para trás

**Comment by igr-santos** [comment]
@rolivegab é preciso entender mais afundo esse problema, pois tecnicamente usa-se o mesmo segredo para gerar as chaves de autenticação, então mesmo se a aplicação utiliza outra API essa deve saber se autenticar com o token passado

**Comment by lpirola** [comment]
problema está em usar api-v3 e api-v2 conjuntamente.
