### ISSUE TITLE
[admin] Deletar uma imagem adicionada pelo slate-editor não funciona em staging

### ISSUE THREAD

**Issue by rolivegab** [nossas/bonde#1075]
### Contexto

Dentro de uma mobilization, anexar uma imagem, clicar nela e tentar deletar. Nada acontece.

### Exemplo

![image](https://user-images.githubusercontent.com/7359906/58121638-401b5500-7bde-11e9-96ab-8193eb1e57e3.png)

**Comment by igr-santos** [comment]
@rolivegab tem como informar a saída de console do navegador?

**Comment by rolivegab** [comment]
Aí é que está, não dá saída nenhuma e não executa nenhuma ação
Inclusive, é o caminho que o tal usuário anônimo segue de acordo o relatório do sentry.io da issue #1074.

Se você seguir os passos dos cliques (dá pra achar com document.querySelectorAll no console):

![image](https://user-images.githubusercontent.com/7359906/58129536-4fa39980-7bf0-11e9-892c-038490e23064.png)

vai conseguir ver os dois problemas, tanto esse, quanto o da issue #1074

**Comment by igr-santos** [comment]
não consegui reproduzir essa issua no meu ambiente de desenvolvimento, acho que vale esperar mergear algumas correções em develop e testar de novo no ambiente de staging

**Comment by rolivegab** [comment]
Certo, pode ser, mas qualquer coisa fala comigo que eu mostro o problema
aqui no meu ambiente local, idêntico como está no staging.
