### ISSUE TITLE
TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#1078]
https://sentry.io/organizations/nossas/issues/1037212489/?referrer=github_plugin

```
TypeError: Cannot read property 'push' of undefined
  at apply (mobilizations/widgets/__plugins__/pressure/components/__pressure__.js:144:22)
...
(10 additional frame(s) were not displayed)
```

**Comment by igr-santos** [comment]
Existem alguns arquivos que estão `browserHistory` para fazer redirecionamento por API, porém o browserHistory foi removido do react-router, é preciso aplicar a nova estrategia adotada pela biblioteca.

**Comment by lpirola** [comment]
@igr-santos vou passar para o @rolivegab, ok?

**Comment by igr-santos** [comment]
não, tô resolvendo já. eu não tinha assininado a issue?
