### ISSUE TITLE
Add to widget fields to capture users identification

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#109]
- [x] 2 new inputs will be added to user's view of widget;
- [x] Must sync new subscriptions into mailchimp segment

**Comment by gabrielrtakeda** [comment]
# Introduction

It should capture users data when use match widget.

## API Structure

On the API, the Activist's table follows the fields below:

| field | type |
| --- | --- |
| id | int |
| name | string |
| email | string |
| phone | object |
| document_number | string |
| document_type | string |
| created_at | timestamp |
| updated_at | timestamp |

## Input fields

The `name` input should be the full name or we must add one more input, splitting in `firstname` and `lastname` and when we go to save that data, we concatenate each other.

### Current
- The current MatchWidget layout is following below:

<img width="318" alt="screen shot 2016-08-02 at 20 44 46" src="https://cloud.githubusercontent.com/assets/5435389/17349184/2dc05fb6-58f2-11e6-9e75-2eaaa9f141c6.png">

### With inputs to capture users data
- **Update:** After selects the options of match, the `name` and `email` inputs should be shown:

<img width="312" alt="screen shot 2016-08-03 at 13 04 12" src="https://cloud.githubusercontent.com/assets/5435389/17372593/eb52f420-597a-11e6-8797-c5f7ab1efad4.png">
- After all data has been filled up, the "Match" button enables:

<img width="314" alt="screen shot 2016-08-02 at 20 59 14" src="https://cloud.githubusercontent.com/assets/5435389/17349433/119eb560-58f4-11e6-85e0-1311a69fd00e.png">

### With inputs error messages
- If user inputs an email that not corresponds to correct email format, it shows an error message.

<img width="313" alt="screen shot 2016-08-03 at 13 52 02" src="https://cloud.githubusercontent.com/assets/5435389/17374115/800bda72-5981-11e6-83e5-492e09e42339.png">

## Code

The inputs may be rendered by a custom component `<Input />` inside `/app/scripts/components/MatchWidget` directory. Something like jsx code below:

``` jsx
<Input
  uid="input-match-name"
  type="text"
  label="Nome"
  placeholder="Insira aqui seu nome"
  required={true}
  onChange={e => { this.setState({ name: e.target.value }) }}
  show={!!selectedChoiceA}
/>
```

**Comment by gabrielrtakeda** [comment]
The error message is a reusable component that uses into `FormWidget` component too. For that reason, i'll isolate it in a separated file inside `/app/components/FormUtil/Error`.

#### Code example

``` jsx
<Error
  message="Email inválido"
  classes={['mb1', 'orange', 'regular']} // {array} optional, for more customizability
  styles={{ backgroundColor: '#fff' }} // {object} optional, for more customizability
/>
```

This file structure follows the conventions of [mern-starter](https://github.com/Hashnode/mern-starter) boilterplate for reusable components. (thanks to @igr-santos for the advices)

The `<Input />` component may be inside that structure too.

**Comment by gabrielrtakeda** [comment]
Needs to split `<Input />` component in `<Input />` and `<Label />` components.
Current `<Input />` component don't follow the SRP (Single Responsibility Principle), which render an input and label element. 😞

**Comment by igr-santos** [comment]
Need have a responsibility to SRP (Single Responsibility Principle), I guess split code not is better choice, but a container with Input and Label according of props received a good choice

**Comment by gabrielrtakeda** [comment]
## Suggestion

The current `<Input />` component renders the html below:

``` jsx
<div className="mb2" style="display: block">
  <label className="h4 caps bold mb1">Nome *</label>
  <input
    id="input-match-name"
    className="field-light block full-width h3"
    onChange="function()"
    placeholder="Insira seu nome aqui"
    type="text"
    required="false"
  />
</div>
```

## Options

The options a have are:
- Pass `<label>` element as a children of Input but, this isn't a good idea semantically. And because i don't want to write the line `<label className="h4 caps bold mb1">Nome *</label>` every time i need the `<label>` element.

``` jsx
<Input
  uid="input-match-name"
  type="text"
  placeholder="Insira aqui seu nome">
  <label className="h4 caps bold mb1">Nome *</label>
</Input>
```
- Or split it and treat it as a separated components.

``` jsx
<Label text="Nome *" />
<Input
  uid="input-match-name"
  type="text"
  placeholder="Insira aqui seu nome"
/>
```

## Motivation

It's more a question of standardization than how components will work together.. I don't want to write every the same css classes to renders a label that already exists in another part of application.

**Comment by gabrielrtakeda** [comment]
Needs to migrate MatchWidget to new modularized structure.

**Comment by gabrielrtakeda** [comment]
Needs to refactor action types, which actually is included in `WidgetActions.js` file.

**Comment by gabrielrtakeda** [comment]
Needs to create an endpoint to save user and selected match data. The payload may be something like this:

#### Payload

``` json
// This is what API will receive as payload.
{
  "activist_match": {
    "match_id": 72,
    "activist": {
      "name": "Gabriel Ramos Takeda",
      "email": "gabriel@nossascidades.org"
    }
  }
}
```

And, how we will send these data on the "activists view" side, we'll don't have any credential data. So the API must don't needs to authenticate the post request. (Maybe warning?)

**Comment by gabrielrtakeda** [comment]
API commit: https://github.com/ourcities/hub-api/commit/e91e9d082423e0f6b77a9062af226b6a21798d9e

**Comment by gabrielrtakeda** [comment]
Needs to merge [add-modularized-structure](https://github.com/ourcities/hub-client/tree/add-modularized-structure) into [add-match-widget](https://github.com/ourcities/hub-client/tree/add-match-widget) branch and adapt according to the new modularized folder structure.

**Comment by gabrielrtakeda** [comment]
Needs to add lastname to sync with mailchimp.

#### Screenshot:

<img width="313" alt="screen shot 2016-08-09 at 13 34 48" src="https://cloud.githubusercontent.com/assets/5435389/17524736/2543debe-5e36-11e6-961c-4891e9bddaf3.png">
