### ISSUE TITLE
Migrar admin-canary para utilizar create react app 3

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#1097]
#1041

Definição de pronto:

## Apps

- [x] Atualização do admin-canary para utilizar create react app 3
- [x] Atualização do admin para utilizar create react app 3
- [x] Migrar os testes do admin para padrão CRA
- [ ] Integração do Yarn Workspaces com lerna;

## Bibliotecas

- [ ] Padronizar a forma de exportar como biblioteca bonde-styleguide e bonde-webpage
- [ ] Padronizar utilização do styleguidist

Definição de pronto:

- [ ] Tempo de Build <= 5min

**Comment by lpirola** [comment]
@alalbux @rolivegab para cada todo dessa issue, podem criar issues novas.

Seria importante também comentar a estratégia adotada na resolução da issue, afim de conseguirmos debater a estratégia.

No caso de migrar para create react app 3, eu começaria um projeto do zero e iria adicionando o código e as dependências aos poucos.

Alguém tem outra ideia?

**Comment by rolivegab** [comment]
@lpirola, acredito que não seja necessário recriar o projeto para o package bonde-admin, pois o mesmo não sofreu eject. Nesse caso, o processo de migração já está bem descrito na documentação e acredito que ocorrerá de forma simples e com poucos (senão nenhum) problema.

Entretanto, já sobre o bonde-admin-canary, irei estudar mais a fundo qual será a melhor forma de fazer o upgrade do create-react-app, pois deu para ver que ele sofreu o eject, e nesse caso, a documentação do cra trás duas possibilidades:

1) Voltar até um commit em que não tenha sido feito o eject ainda, atualizar o create-react-app, e então aplicar novamente as mudanças 1 a 1 e ir resolvendo os problemas
2) criar um projeto zerado no create-react-app-3, ir adicionando o código fonte e dependências aos poucos e ir resolvendo os problemas que vierem a aparecer.

Acredito que a segunda opção seja melhor, mas isso me faz pensar, principalmente, em qual foi o motivo de ter acontecido o eject no bonde-admin-canary. São realmente poucos os casos em que é necessário dar um eject, e inclusive é algo que não é indicado de ser feito inclusive pela própria documentação do boilerplate.

**Comment by rolivegab** [comment]
Apenas para reforçar a pergunta e iniciar a discussão:

Você sabe por motivo foi necessário que o bonde-admin-canary passasse pelo processo de eject do create-react-app? Existiu alguma necessidade que a estrutura do projeto não atendia?

**Comment by alalbux** [comment]
A ideia pelo que eu entendi é que quando é usando o eject ele desconecta o projeto por completo o react-scripts. Por isso a ideia de ir migrando os pacotes e o código @rolivegab. Como conversei com o @lpirola ambos os projetos foram ejectados. Acho que podemos seguir esse caminho por mais trabalhoso que seja já que isso é um débito técnico e como a ideia é melhorar o tempo de build dos projetos. Acho que vale o emprego de tempo.

**Comment by rolivegab** [comment]
@alalbux, o bonde-admin não sofreu eject
