### ISSUE TITLE
Adicionar opção de doação recorrente no pós-doação

### ISSUE THREAD

**Issue by alalbux** [nossas/bonde#1111]
### Contexto
Será desenvolvida uma opção no admin para que na hora de criar um bloco de crowdfunding o usuário teria a opção de adicionar no pós-doação a doação recorrente
- Doações únicas
- Recorrencia 30 dias

previsão de entrega **10/06/2019** 

### Exemplo
![Captura de Tela 2019-06-04 às 08 22 51](https://user-images.githubusercontent.com/38147979/58875457-ff254500-86a1-11e9-8937-411040f0fc91.png)
![Captura de Tela 2019-06-04 às 08 24 03](https://user-images.githubusercontent.com/38147979/58875536-33006a80-86a2-11e9-9639-4b5c0353eda2.png)

### Requisitos e Critérios de Aceite
- [ ] Ajustar visual do componente de doação simples para atender melhor às especificações.
- [ ] `FormFinishMessage` adicionar opção `post-donation` quando tiver no `DonationSettingsFinish`
- [ ] Adicionar componente de `FinishPostDonation` no preview do `FormFinishMessage`
- [ ] criar componente `FinishPostDonation`
- [ ] no `DonationPlugin` adicionar o `FinishPostDonation` no `renderThankyouText`
- [ ] criar uma action pra conversão da `donationTransactionConvert`
- [ ] importar plugin no Mobilization connected

**Comment by rolivegab** [comment]
No bonde-admin, há uma configuração de tipo de doação:
![image](https://user-images.githubusercontent.com/7359906/58950813-fd24ba00-8765-11e9-8f37-d03d00554c8f.png)

Acredito que uma forma de deixar o processo mais simples para o usuário seja remover totalmente o campo (apenas na parte visual), e trocar por um único campo que vai conter apenas um checkbox:

- [ ] mostrar apenas opção para doação recorrente

Isso atenderia os requisitos do problema e deixaria mais claro para o usuário o que vai acontecer com o componente. Além do mais, também não precisaria mexer em nada no banco de dados  para ajuste de funcionalidade, pois nesse novo módulo se comporta de forma idêntica tanto para tipo de doação `unique` quanto para `user chooses`. No caso do checkbox acima, se ele for marcado o componente de pós-doação não aparece.
