### ISSUE TITLE
[webpage] alterar lógica de submissão na widget de doação quando marcado pós ação

### ISSUE THREAD

**Issue by igr-santos** [nossas/bonde#1125]
### Contexto

**Issues relacionadas**: #1111

Hoje a API-v1 já funciona com a lógica de doação única recorrente, com isso em mente é preciso implementar uma lógica na submissão de uma doação.

### Requisitos e Critérios de Aceite

- [ ] Ao selecionar a opção doação recorrente (`donation-recurrent`) no tipo da mensagem de pós ação (`finish_message_type`) deve alterar o fluxo de doação para pós confirmação de recorrência.
- [ ] Deve executar fluxo de doação única quando usuário não confirmar recorrência
- [ ] Deve executar fluxo de doação recorrente quando usuário confirmar recorrência

**Comment by rolivegab** [comment]
E se o usuário fechar a janela antes de responder se deseja a recorrência ou não?
