### ISSUE TITLE
Documentação do bonde-client

### ISSUE THREAD

**Issue by alalbux** [nossas/bonde#1126]
### Contexto
A ideia é discutimos qual é a melhor abordagem de desenvolvimento no bonde-client, acredito que deveriamos fazer um levantamento dos scripts, arquitetura e de padrões de desenvolvimento em cada projeto, acredito que a adição de um readme nos projetos quando publicado no npm trazendo uma prévia do uso dele nos projetos dentro do repo. 

Dentro dessa ideia é a gente consegui que a informação sobre os projetos estejam mais claras e que tenha fácil consulta pra que não fique centralizado o conhecimento nas pessoas que desenvolveram. 

**Vamos criar issues apartir do andamento dessa análise**

*Essa issue estará em análise, a ideia é que todos interajam e deem sua opnião do que acharia que seria bom adicionar de informação*

**Comment by vivianedias** [comment]
**PR** -> https://github.com/nossas/bonde-client/pull/1269
