### ISSUE TITLE
[ admin-canary ] Tooltip na home não está posicionado corretamente

### ISSUE THREAD

**Issue by alalbux** [nossas/bonde#1127]
### Contexto
Quando está num novo acesso do `admin-canary` ele quebra o fluxo no qual o `Tooltip` deveria está posicionado alinhado a mobilizações, mas ela está configurado no rodapé e não é mostrado no primeiro frame de tela.

### Exemplo
![Captura de Tela 2019-06-07 às 15 31 50](https://user-images.githubusercontent.com/38147979/59126040-6e1ccb00-893a-11e9-80d8-ec552781120c.png)

### Descrição técnica
Reposicionar `Tooltip` em mobilizações

### Requisitos e Critérios de Aceite
- [ ] Tooltip em mobilizações

**Comment by lpirola** [comment]
foi removido o tour
