### ISSUE TITLE
[admin] Após convidar usuário para comunidade aviso de sucesso não aparece

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#1129]
### Contexto

Nenhum notificação tem sido apresentada dentro do `bonde-admin`.

### Descrição técnica

Um local onde pode ser testado é no convite de mobilizadores para a comunidade, deve aparecer uma notificação de sucesso ou erro ao convidar um e-mail.

### Requisitos e Critérios de Aceite

- [ ] Apresentar notificações em todos os momentos em que notificações forem utilizadas dentro do `bonde-admin`

**Comment by igr-santos** [comment]
Nós usamos hoje no `bonde-admin` https://github.com/LouisBarranqueiro/reapop, e no `bonde-admin-canary` usamos o https://github.com/fkhadra/react-toastify.

Acho que vale levantar o quanto tempo demora para alterar o a biblioteca o reapop é bem verbose, acho que o toastify é mais fácil de usar.

**Comment by igr-santos** [comment]
Houve reclamação do mal funcionamento no momento de fazer o convite para usuários, foi reportado:

"""
A pessoa recebe o convite, clica no link e pede pra ela fazer o login, quando ela faz, não aparece a comunidade que ela aceitou
"""

**Comment by alalbux** [comment]
Desde quando foi atualizado o react-scripts e removido o webpack ele não consegue compilar os arquivos que estão em scss. Estou validando se as libs que estão no admin que já fazem isso precisam ser configuradas pra fazer essa compile do pra css. 

- testei criar um script pra compilar o sass com o node-sass, mas nao resolveu o problema
- Aparentemente o middleware está funcionando normalmente, fiz uns testes nele pra ver se era algum problema no fluxo de comunicação
- Refiz a instalação do tema (WIP)

**Comment by alalbux** [comment]
testando https://github.com/LouisBarranqueiro/reapop/issues/82#issuecomment-418858386

**Comment by alalbux** [comment]
Libs que poderiamos usar:

https://github.com/fkhadra/react-toastify
https://github.com/igorprado/react-notification-system

**Comment by lpirola** [comment]
@alalbux como conversamos na reunião, foco agora é trocar a parte de notificação na hora de fazer o download de relatórios para utilizar o react-toastify.

Com isso conseguiremos prever melhor quanto tempo mais é ncessário para migrar as outras partes da plataforma que utilizam esse sistema de notificação
