### ISSUE TITLE
[admin-canary] Erro query TrendingMobilizations

### ISSUE THREAD

**Issue by alalbux** [nossas/bonde#1142]
### Contexto
Algumas querys precisam ser migradas para fazermos o rollout para a api-v3, uma delas é migrar TrendingMobilizations para api-v3. Atualmente ele é usado na home do admin-canary.

### Exemplo

`{"errors":[{"message":"Cannot query field \"trendingMobilizations\" on type \"Query\". Did you mean \"userMobilizations\"?","locations":[{"line":2,"column":3}]}]}`

```
TrendingMobilizations
```

### Descrição técnica

```
TODO - Sugestão de interface
```

### Requisitos e Critérios de Aceite

- [ ] Migrar query TrendingMobilizations para api-v3

**Comment by igr-santos** [comment]
@alalbux dá uma checada na nova versão `feature/chatbot` do `bonde-graphene`, lá você pode verificar a assinatura da query `trendingMobilizations`.

**Comment by alalbux** [comment]
Em staging a query não parece que esteja funcionando pela quantidade de itens no banco, ele retorna um timeout, entao idealmente seria necessario mexer na query dentro do `bonde-graphene` para melhorar a perfomance dela.

**Comment by alalbux** [comment]
https://github.com/nossas/bonde-graphene/blob/70d4418a8a6cee67d19721eb969e231b16c583fd/bonde_graphene/schemas/mobilization/query.py#L26
