### ISSUE TITLE
[admin-canary] fluxo de registro de novo mobilizador

### ISSUE THREAD

**Issue by alalbux** [nossas/bonde#1145]
### Contexto
Migrar fluxo de registro de usuário do admin para o admin-canary. Certificar que fluxo de usuário adicionado dentro do fluxo de comunidade via convite pelo admin

- Migrações da api-v2 para a api-v3 (Já existe a mutation na api-v3)
- Fluxo de convites por uma comunidade (Aplicado no api-v1)
- Adicionar fluxo de configuração no admin-canary (Mobilizadores)

### Exemplo
![Captura de Tela 2019-07-11 às 19 08 48](https://user-images.githubusercontent.com/38147979/61088763-753e6980-a40f-11e9-9438-7335e8c7f828.png)

### Descrição técnica
Adicionar uma `scene` dentro do contexto `Logged`, criar rota `settings`, adicionar ao `Header` navegação por `renderTabs`.

### Requisitos e Critérios de Aceite

- [ ] Interface no front com formulário de adição de mobilizador
- [ ] Migrar comunição para api-v3
- [ ] Confirmar fluxo de envio de email e validação de usuário

**Comment by lpirola** [comment]
@alalbux poderia revisar o fluxo de criação de usuário e convite de comunidade atual antes de fazer a migração?

 Pois acredito que antes de fazer a migração é importante ter certeza que o fluxo atual está funcionando perfeitamente.

**Comment by alalbux** [comment]
desenvolvimento na `feature/settings`

**Comment by lpirola** [comment]
despriorizado pois não faz sentido nesse momento.
