### ISSUE TITLE
[admin] Estilo da página de envio de mensagem em massa não está correto

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#1148]
A página não está com os componentes no estilo correto, pode ser vista na rota /bot se vc tiver a comunidade BETA selecionada.

**Comment by vivianedias** [comment]
Preciso do design pra corrigir. Não consegui achar no zeplin também :disappointed:

**Comment by vivianedias** [comment]
**PR** -> https://github.com/nossas/bonde-client/pull/1265
