### ISSUE TITLE
[beta][canary] Adicionar validação e mais informações ao input de identificador

### ISSUE THREAD

**Issue by igr-santos** [nossas/bonde#1150]
### Contexto

No formulário para adicionar uma campanha, o input de identificador possui 2 possibilidades de erro que não são validadas no hoje:

* Identificador deve ser único
* Identificador não deve possuir espaçamento

**Comment by rolivegab** [comment]
@igr-santos , Identifiquei que a entrada de um valor com espaçamento não ocasiona erros, isso precisa mesmo ser validado?

EDIT: falha minha, confundi o problema dessa issue e acabei resolvendo outra issue por ter lido errado.

**Comment by rolivegab** [comment]
![image](https://user-images.githubusercontent.com/7359906/60444058-cf128880-9bf2-11e9-9a5d-5b465de87071.png)
@igr-santos, essa é a mensagem de erro que retorna quando envio uma requisição com identificador duplicado.

Nesse caso, eu posso tentar mostrar uma mensagem de erro baseado nessa string que é retornada, buscando pela substring "duplicate_key" e etc, tentando tratar no front-end, ou essa mensagem de erro pode vir direto do back-end.

Qual abordagem você acha melhor?
E no caso, de a mensagem de erro vir do back-end, posso tentar fazer a alteração no bonde-graphene?
