### ISSUE TITLE
[beta][bot] problemas quando atualiza uma campanha, o servidor do bonde-bot não é atualizado

### ISSUE THREAD

**Issue by igr-santos** [nossas/bonde#1152]
### Contexto

Visando aproveitar a maneira como o bot para comunicação com facebook estava implementada, o bonde-bot mantem uma rota em um server `express` para cada configuração de bot no bonde.

Quando o server do bot é iniciado ele faz uma atualização do seu script a partir da base de dados, utilizando o acesso pela API-v3 (`bonde-graphene`), após o usuário dentro do `bonde-admin-canary` realizar uma alteração em qualquer informação no módulo do chatbot é necessário reinicializar o serviço do bonde-bot para que ao iniciar ele faça a atualização do script.

### Requisitos e Critério de aceite

- [ ] Atualizar script entre `bonde-admin-canary` e `bonde-bot` sem necessidade de reiniciar o serviço `bonde-bot`

**Comment by igr-santos** [comment]
@lpirola sugeriu criar um comando via slack para reiniciar o bonde-bot, possibilitando a edição do script e a utilização temporaria do comando para atualizar a interação com o FB

**Comment by lpirola** [comment]
@igr-santos A solução será fazer uma chamada direta para o rancher via api rest. Criaremos um botão na interface de publicação para indicar o gatilho que irá fazer isso.

**Comment by lpirola** [comment]
foi resolvido com a estratégia de utilizar a tecnologia de websocket para receber a atualização em tempo real
