### ISSUE TITLE
[beta][admin-canary] Ajustes visuais no fluxo de conversa adicionando o bonde-diagram

### ISSUE THREAD

**Issue by alalbux** [nossas/bonde#1159]
### Contexto
Ajustes visuais na edição de conversa

### Exemplo

![Captura de Tela 2019-07-24 às 09 56 42](https://user-images.githubusercontent.com/38147979/61795407-bf552100-adf9-11e9-9355-c7439d9dac65.png)
![Captura de Tela 2019-07-24 às 09 57 07](https://user-images.githubusercontent.com/38147979/61795408-bf552100-adf9-11e9-92e6-e9cb9da1a309.png)
![Captura de Tela 2019-07-24 às 09 57 25](https://user-images.githubusercontent.com/38147979/61795410-bf552100-adf9-11e9-8930-486779341e9f.png)
![Captura de Tela 2019-07-24 às 10 02 59](https://user-images.githubusercontent.com/38147979/61796384-ac435080-adfb-11e9-8d77-83e018e25e43.png)

### Requisitos e Critérios de Aceite

- [ ] Adicionar botão `salvar` no Header da página, com persistencia dos dados na API hasura
- [ ]  Adicionar botão `salvar e publicar` no Header da página, com persistencia dos dados na API hasura
- [ ] Estilizar `Card` de acordo com exemplo no figma
- [ ] Adicionar botões de zoom in e zoom out

**Comment by igr-santos** [comment]
@alalbux o fluxo é `auto-save` cada balão (mensagem) cuida de como deve salvar / editar, não precisando haver o botão de Salvar, pois quando você adicionar uma nova mensagem ela já está sendo inserida no banco de dados e atualizada no front.

O fluxo é -> Salvar no banco de dados -> Retornar a resposta -> Atualizar GraphQL com novas informações

**Comment by igr-santos** [comment]
@alalbux estilizar card é um problema grande, já foi discutido isso no passado com o @lpirola, hoje a biblioteca que usamos para renderizar a árvore, utiliza a montagem em SVG e não nos permite um layout tão adaptável como desenhado no figma.

Você pode ir mais afundo olhando direto para biblioteca que usamos https://github.com/bkrem/react-d3-tree

**Comment by alalbux** [comment]
@igr-santos Dei uma olhada nessa lib acha que orna no nosso contexto? https://github.com/DrummerHead/react-flow-diagram

**Comment by alalbux** [comment]
Vou fazer uns testes depois com calma e vejo se encaixa

**Comment by lpirola** [comment]
A história da lib é legal:

```
In a Trailblazer related project I had the task of creating an editing environment surrounding bpmn-js which was the first diagramming library we used. bpmn-js proved to be a feature rich library, but extending to add the features we wanted proved to be practically impossible, coupled with dwindling documentation. It's still a great option if you're not thinking of adding your own types of entities or swerving from the BPMN model at all.

After assessing many diagramming libraries available, my second go after bpmn-js was react-diagrams; which worked pretty well, had modern JS standards and was more extensible. However the source of truth (model) was scattered through many object's internal state and getting to the underlying data proved difficult in many scenarios.

I was quite happy with the idea of using a time-tested open source library, but the options available left me making the decision to build an alternative. I hope it's useful for you!
```

amanhã podemos falar mais dela na reunião diária.

**Comment by alalbux** [comment]
Essa issue representa os ajustes que fizemos no `bonde-diagram`, trocamos a lib para a https://github.com/projectstorm/react-diagrams para ter mais liberdade desenvolvimento do fluxo de conversa.
