### ISSUE TITLE
[beta][admin-canary]  Ajuste modal de criação de campanha no fluxo de conversa

### ISSUE THREAD

**Issue by alalbux** [nossas/bonde#1161]
### Contexto
Ajustes visuais e no fluxo de criação de mensagem no Fluxo de Conversa

### Requisitos e Critérios de Aceite

- [ ] Adicionar traduções
- [ ] Adicionar test de renderização e dos métodos esperados
- [ ] Verificar necessidade de IDENTIFICADOR
- [ ] Estilizar o `CreateFlowModalForm` de acordo com layout do figma

**Comment by igr-santos** [comment]
@alalbux o identificador é necessário para identificação de cada campanha, é como se fosse uma tag e deve ser única por campanha, coloquei isso nas mãos do usuário pois eles tem uma maior noção de como identificar cada campanha.

Podemos criar automaticamente isso também, mas vai ser preciso checar isso tanto no front-end quando no backend da API-v3. Hoje a API-v3 já retorna um erro tratado pelo @rolivegab quando esse campo não é único.

**Comment by rolivegab** [comment]
Dúvida, o campo identificador será escondido mesmo?
E outra, caso sim, posso usar um uuid() para gerar um identificador automaticamente no front-end? Ou é melhor tratar isso no back-end?
Além do mais, talvez caso não seja usado, será que não seria possível excluir logo a coluna do banco de dados?
