### ISSUE TITLE
[beta][admin-canary] Ajuste CreateMessageModalForm no fluxo de conversa

### ISSUE THREAD

**Issue by alalbux** [nossas/bonde#1162]
### Contexto
No fluxo de conversa apareceriam as opções abaixo e não um modal como atualmente é feito.

### Exemplo

Atual:
![Captura de Tela 2019-07-02 às 17 07 16](https://user-images.githubusercontent.com/38147979/60543365-88a15480-9cec-11e9-984b-bee6348349ac.png)

Esperado:
![Captura de Tela 2019-07-02 às 17 13 53](https://user-images.githubusercontent.com/38147979/60543482-cd2cf000-9cec-11e9-85d7-c3120d63912f.png)

## Requisitos e Critérios de Aceite

- [ ] Adicionar traduções
- [ ] Estilizar de acordo com o figma / Mantendo modal a principio
- [ ] Adicionar test de renderização e dos métodos esperados

**Comment by lpirola** [comment]
@alalbux acredito que mudamos para modal para ser mais rápido de apresentarmos o funcionamento completo do chatbot.

Podemos despriorizar essa alteração até termos o fluxo completo funcionando.

**Comment by alalbux** [comment]
Sem problemas, só pra não cair no esquecimento

**Comment by igr-santos** [comment]
Acho que uma melhoria que não demanda muito tempo, é alterar o input do tipo de mensagem de um select textual para um select de botões utilizando icones por exemplo.

**Comment by alalbux** [comment]
essa issue está na contida nessa #1159 que vai mudar o fluxo de conversa para o uso do bonde-diagram
