### ISSUE TITLE
[admin-canary] Graphql error Signature has expired

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#1167]
### Contexto
Ao tentar acessar o admin-canary com token expirado fico preso na página de carregando

### Exemplo
```{"jwtToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJ1c2VyX2lkIjozMSwiaWF0IjoxNTYwMjY0MjY2LCJleHAiOjE1NjAzNTA2NjYsImF1ZCI6InBvc3RncmFwaGlsZSIsImlzcyI6InBvc3RncmFwaGlsZSJ9.K6PVfVeXZ3dkAQqhJK4483LnV9HwFUGWJKP6yak1Cis"}```

### Descrição técnica
Quando o token utilizado para fazer a requisição dos dados do usuário logado está expirado, deveríamos ter um tratamendo dentro do admin-canary.

### Requisitos e Critérios de Aceite
Utilizando o token de exemplo em staging, ao recarregar a página preciso ser direcionado para página de login para pegar um token válido.

**Comment by igr-santos** [comment]
@lpirola isso acontece em qual branch? Lembro de já ter corrigido esse problema.

https://github.com/nossas/bonde-client/blob/feature/chatbot/packages/bonde-admin-canary/src/services/auth/AuthProvider.js#L26
