### ISSUE TITLE
Modernização da visão pública da Mobilização

### ISSUE THREAD

**Issue by rolivegab** [nossas/bonde#1174]
### Contexto

Essa issue irá conter o estudo, ideias e discussões para tentar reduzir o bundle size, em especial do bonde-webpage, com o objetivo de tornar melhor a experiência do usuário, e permitir o carregamento inicial do sistema mais rápido, e consumindo menos dados de internet.

Inicialmente, procurei instalar alguma ferramenta para uma análise mais profunda da build do bundle, tentei sem sucesso utilizar o webpack-analyzer. Os tutoriais que ensinam a utilizar com o create-react-app sem a necessidade do processo de eject já não estão mais funcionando. O processo de build com o argumento `--stats` não mais gera um arquivo `build-stats.json` na pasta `build/*`.

Eventualmente descobri que o suporte ao webpack-bundle-analyzer foi descontinuado em razão da preferência de uma outra ferramenta, o *souce-map-explorer*. Que possui funcionalidade semelhante, mas ele trabalha em cima dos source-maps para descobrir o tamanho do bundle-size de todo o ecossistema. Nesse caso, para fazer funcionar, obviamente, você precisa buildar o bonde-webpage com o comando -s, o qual insere os source-maps nos arquivos de build. Isso não altera no tamanho do bundler final de análise, pois os arquivos .js.map não são levados em conta no cálculo.

A seguir a imagem gerada pelo souce-map-explorer aplicado em cima do bonde-webpage: 
![image](https://user-images.githubusercontent.com/7359906/60811413-92500f80-a165-11e9-9d77-7f4b52d5994a.png)

O que dá para notar é que não acho que deveria haver muita preocupação com relação ao código do bonde-webpage, só notei que dava para fazer a minificação do código.

Após mover as configurações para o .babelrc e após realizada a minificação do código, observou-se uma redução de 27,5% do bundle size, vide imagem:

![image](https://user-images.githubusercontent.com/7359906/60825239-a275e800-a181-11e9-8489-c9422fefbb56.png)

Vou abrir um PR com todas as mudanças realizadas, além dos comandos para analizar o tamanho dos pacotes para cada um dos packages do bonde-client.

Irei aos poucos adicionando outros avanços aqui.

**Comment by rolivegab** [comment]
Atualização:
Notei que o souce-map que o babel está fazendo não está conseguindo cobrir todo o código..
Tem muitas mensagens de warning ao rodar o source-map-explorer, e após mudar o tipo de source-map do babel, alterando a option "sourceMaps" de `true` para "both", o bundle size triplicou de tamanho, e mais informações apareceram no navegador.

Estou buscando me informar melhor em como utilizar o source-map-explorer da forma correta, e melhorar o processo de build (para o bonde-webpage).

Nova análise: 

![image](https://user-images.githubusercontent.com/7359906/60826783-0a79fd80-a185-11e9-98ec-2b6479b126d5.png)

Correção... Provavelmente o parâmetro "both" não é o ideal...
Ele inclui o sourcemap dentro do arquivo final em vez de um arquivo separado.

**Comment by rolivegab** [comment]
Estou convertendo o bonde-webpage para usar o webpack, por ter muito mais opções e ser muito melhor documentado.

**Comment by lpirola** [comment]
@rolivegab o caminho talvez, possa ser pela https://github.com/zeit/next.js/tree/canary/packages/next-bundle-analyzer

**Comment by alalbux** [comment]
existem algumas diretrizes que a google adaptou do pwa para single pages que encaixa muito bem nessa otimização https://developers.google.com/web/fundamentals/performance/prpl-pattern/

**Comment by alalbux** [comment]
Exemplo pra otimização do nextjs https://github.com/drenther/next-pwa
Existe alguns conceitos que dá pra aplicar no webpage por exemplo, mas talvez a falta de um webpack seja ruim pra criar os bundle separados. Mas achei esse exemplo aqui bem documentado https://github.com/gabrielmicko/react-create-app-pwa

**Comment by alalbux** [comment]
Tem esse artigo do caso aplicado que da uma direção bem boa https://medium.com/dev-channel/treebo-a-react-and-preact-progressive-web-app-performance-case-study-5e4f450d5299

**Comment by alalbux** [comment]
Tava lendo algumas coisas sobre otimização de bundle e esbarrei em algums repositórios interessantes https://github.com/hanford/next-offline, é um plugin que a ideia dele é trazer o PWA pro Nextjs e https://github.com/gaearon/react-hot-loader que seta e impede ficar dando fetch sem necessidade. Vou fazer um estudo dentro do `bonde-public` como esses caras poderiam se encaixar no nosso contexto

**Comment by vivianedias** [comment]
**BONDE-WEBPAGE**

Hoje o package não usa nenhum tipo de ferramenta de otimização de build, apenas compila o código para CommonJS usando o babel.

Segundo [o próprio medium do webpack](https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c), é recomendado usar o Rollup p/ bibliotecas por conta de umas features que ele já tem por padrão. O bonde-webpage é uma biblioteca, portanto acredito que faça sentido usarmos o Rollup e no melhor dos casos o `tsdx` que já é um boilerplate que temos usado.

Esse passo tem um enfoque em melhorar o bundle size, o que também impacta no carregamento da página em si, mas acredito que outras técnicas também podem ser aplicadas no webpages p/ melhorar a performance - vou listando elas aqui quando encontrá-las.

**Comment by lpirola** [comment]
ótima análise @vivianedias.

ela nos leva a outra questão: a refatoração do componente de webpage.
