### ISSUE TITLE
Configurar Google Optimize

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#1175]
# Contexto 

Para iniciarmos a utilização do Google Optimize, o primeiro passo é adicionar o script abaixo:

```<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-26278513-30"></script>
<script>
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());

gtag('config', 'UA-26278513-30', { 'optimize_id': 'GTM-W4T6JCX'});
</script>```


Essa biblioteca pode facilitar o trabalho https://github.com/hudovisk/react-optimize

**Comment by lpirola** [comment]
https://www.npmjs.com/package/react-experimentify

**Comment by lpirola** [comment]
![image](https://user-images.githubusercontent.com/14948/60896491-ce09d880-a23c-11e9-9e4a-53aedbbe2f7d.png)

curiosidade sobre essa funcionalidade

**Comment by rolivegab** [comment]
Após estudar sobre o Google Optimize, a sobre a biblioteca já utilizada no bonde-public, e tendo o entendimento de que o único requisito para o uso do google optimize é ter o google analytics integrado ao site, mais a adição do id do google-optimize, estou integrando a adição do id `GTM-W4T6JCX` ao código do bonde-public, e vou referenciar essa issue aqui no PR.

A partir de então, na teoria, conseguiremos fazer a realização do teste AB sem problemas.
