### ISSUE TITLE
[admin] Remover jquery no Form e InputForm 

### ISSUE THREAD

**Issue by alalbux** [nossas/bonde#1198]
### Contexto
Remove jQuery dos componentes de `Form` e `InputForm`

### Requisitos e Critérios de Aceite
- [ ] Remover o jQuery mantendo a funcionalidade

**Comment by vivianedias** [comment]
Acho que essa issue já foi resolvida, única coisa que acho que poderiamos fazer é remover o jquery das dependências do bonde-public também.

**Comment by vivianedias** [comment]
**PR** ->  https://github.com/nossas/bonde-client/pull/1270
