### ISSUE TITLE
[planejamento] bonde-webhook-logs e bonde-webhook-apps

### ISSUE THREAD

**Issue by rolivegab** [nossas/bonde#1230]
### Contexto
Desenvolver o processo de uma estrutura escalável que permita o acoplamento de novos serviços de webhook.

---

#### Primeiro passo
O processo inicia a partir de um serviço **webhook** qualquer. Que deve enviar a requisição para um webserver padrão chamado `bonde-webhook-logs`. Todos os serviços de webhook devem enviar a requisição para esse mesmo webserver.

#### Segundo passo
Esse webserver irá então salvar os dados da requisição recebida sem alteração em uma tabela `Hasura`. A principal e única função do bonde-webhook-logs é realizar o backup desses logs no bonde para possibilitar análises e ter mais uma camada de segurança em cima da arquitetura do webook.

Vale a pena ressaltar que todos os serviços deverão inserir os dados dos webhooks em uma mesma tabela, que será universal para todos. Essa tabela deverá estar marcada com o `track` no Hasura para possibilitar que o banco de dados consiga criar eventos que escutem por mudanças nela.

#### Terceiro passo
Com a tabela sendo escutada pelo Hasura, nesse momento é possível criar um evento do tipo `insert`, que irá identificar toda vez que houver uma inserção no banco de dados e qual foi o dado adicionado. Esse evento, que também é um webhook, deverá enviar uma requisição do tipo POST para um novo webserver com os dados que foram adicionados. Esse segundo webserver por enquanto está com o nome temporário de `bonde-webhook-apps`, e irá realizar o mapeamento das requisições do Hasura, redirecionamento para seus respectivos **webservers finais** onde irão finalmente receber o tratamento e serem consumidas de fato.

Esse processo é importante pois, dessa forma, os webservers finais vão receber apenas a informaçõa que lhes interessa. Ao contrário do que acontece hoje com o `bonde-zendesk` por exemplo, que recebe todas as requisições dos eventos detectados pelo Hasura, independente daquele valor ser útil para o `bonde-zendesk` ou não.

Entretanto, sobre o bonde-webhook-apps ainda não está muito claro qual vai ser a tecnologia usada para desenvolvê-lo, mas existem diversas tecnologias que servem para esse propósito, incluindo a grande maioria dos reverse-proxys mais utilizados hoje em dia no mercado.

**Comment by rolivegab** [comment]
@lpirola vou colocando as atualizações aqui, pode ser?

Meus próximos passos:
- [x] Criar formulário simples no MAUTIC.
- [x] Configurar webhook do formulário.
- [x] Receber formulário no webserver e imprimir na tela.
- [ ] Conectar com hasura local e salvar os dados usando GraphQL.

**Comment by lpirola** [comment]
perfeito @rolivegab

**Comment by lpirola** [comment]
a implementação aconteceu no repositório nossas/bonde-microservices
