### ISSUE TITLE
Pressure Plugin is not sending analytics events

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#1239]
### Descrição técnica

```
TODO - Sugestão de interface
```

### Requisitos e Critérios de Aceite

- [ ]

**Comment by vivianedias** [comment]
Até o momento achei as ferramentas que posso usar pro debug da conexão entre as páginas e o analytics. A partir delas acredito que vai se tornar bem tranquilo identificar o problema e arrumar.

[UPDATE] 
Todo fluxo do analytics foi checado, falta bater os events no Google Analytics do Nossas/Bonde

**Comment by vivianedias** [comment]
Não houve nenhuma alteração do código e foi concluído que o problema não existia, mas acredito que vale mais uma checagem antes do release cobrindo os plugins de doação, formulário e pressão.
