### ISSUE TITLE
After update mobilization facebook share image, the url saved  is //s3 and twitter don't recognize

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#1243]
### Descrição técnica

```
TODO - Sugestão de interface
```

### Requisitos e Critérios de Aceite

- [ ]

https://app.leanboard.io/board/0df2c3ba-677e-4982-be93-85c5ae4b5d6f

**Comment by vivianedias** [comment]
[UPDATE] problema de upload de imagem é provavelmente na api-rest que ao sofrer uma atualização deixou de mandar `https:` com o path da imagem no s3

Isso porque em mobilizações antigas a metatag do `twitter:image` continha o `https`

**Comment by lpirola** [comment]
Corrigido atualizando a variável de ambiente AWS_ENDPOINT com o protocolo https://
