### ISSUE TITLE
[admin-canary] Alterar metódos que usam API-v2 para usar somente metódos da API-GraphQL

### ISSUE THREAD

**Issue by igr-santos** [nossas/bonde#1258]
Objetivo  é remover a dependencia da API-v2 para que possamos trabalhar mais coisas dentro do Hasura.

**Comment by igr-santos** [comment]
- [x] autenticação
- [x] reset de senha
- [x] tags para usuário
- [x] comunidades por usuário
- [x] trending mobilizations
- [ ] registro de usuário?

**Comment by igr-santos** [comment]
@lpirola avançamos mais uma etapa dessa migração!

Agora existem alguns pontos que precisam ser discutidos:

- Permissão de acesso aos dados no modo público
- Permissão de acesso aos dados em modo privado
- Como trabalhar essas permissões dentro do Hasura

**Comment by igr-santos** [comment]
Falta realizar o envio do e-mail para concluir o reset de senha e testar os seguintes fluxos dentro do admin-canary:

> Autenticar Usuário Admin
    > Visualizar Home (Todas as Comunidades e Trending Mobilizations)
    > Visualizar página de edição da Comunidade
    > Visualizar página de edição do Chatbot
    > Navegar para o `bonde-admin`

> Autenticar Usuário Comum
    > Visualizar Home (Comunidades por usuário e Trending Mobilizations)
    > Visualizar página de edição da Comunidade
    > Visualizar página de edição do Chatbot (relacionado as suas comunidades)
    > Navegar para o `bonde-admin`

> Resetar senha seguindo o fluxo:
    > Solicitar token por e-mail
    > Validar token no formulário de alterar senha
    > Alterar senha e redirecionar para Home do admin-canary

Com esses fluxos funcionando essa demanda pode ser considerada entregue.

**Comment by igr-santos** [comment]
Foi corrigido algumas coisas relacionadas a permissão do `common_user` dentro do admin-canary, agora estou trabalhando no disparo de e-mail com instruções para resetar senha usando o mesmo template que era usado quando feito por notifications.

**Comment by lpirola** [comment]
```
11/26/2019 9:42:41 PMFailed with: role "postgraphql" already exists
11/26/2019 10:42:38 PMRunning migration 2019-11-12-184738_drop_postgraphql_authenticate
11/26/2019 10:42:38 PMRunning migration 2019-11-13-113043_add_kind_to_group_tags
11/26/2019 10:42:39 PMRunning migration 2019-11-13-124507_remove_tags_management_on_postgraphql
11/26/2019 10:42:39 PMRunning migration 2019-11-13-124923_remove_user_communities_on_postgraphql
11/26/2019 10:42:39 PMExecuting migration script /volumes/migrations/2019-11-13-124923_remove_user_communities_on_postgraphql/up.sql
11/26/2019 10:42:39 PMFailed with: cannot drop view postgraphql.user_communities because other objects depend on it
```
