### ISSUE TITLE
(Testes) Migrar build da biblioteca bonde-webpage para utilizar tsdx

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#1262]
https://github.com/jaredpalmer/tsdx

**Comment by igr-santos** [comment]
# Editor de conteúdo

- **Mobilização:** http://www.159-mr-apoie.staging.bonde.org/
- **ISSUE:**  Adicionar estilização relacionado a comunidade do meurio (meurio.scss)

**Comment by igr-santos** [comment]
# Pressão por e-mail

- **Mobilização:** http://www.elevacaonajbnao.staging.bonde.org/
- **ISSUE:** Ao submeter o formulário de pressão mesmo com uma resposta ok o pós ação não é apresentado para o usuário final

**Comment by igr-santos** [comment]
# Requisições assincronas

- **Mobilização:** Todos os widgets (bonde-webpage)
- **ISSUE:** Adicionar padrão de loading pra ser reusado nos widgets, usar carregamento no espaço do widget

**Comment by igr-santos** [comment]
Testei os widgets em uma mobilização (http://www.teste-de-widgets.staging.bonde.org/) que eu configurei todas as nossas possibilidades atuais. O problema atual está relacionado a SSR com `styled-components` os componentes renderizam mas a estilização não carrega com build em modo produção, eu já fiz as configurações necessárias na parte do build, mas sem sucesso, estou usando de referência essa leitura: https://dev.to/aprietof/nextjs--styled-components-the-really-simple-guide----101c

**Comment by igr-santos** [comment]
Após algumas pesquisas e testes foi possivel corrigir o problema com a renderização, essa issue foi algo que me esclarei um pouco sobre o processo https://github.com/styled-components/babel-plugin-styled-components/issues/222

Mas a solução do problema se deu alterando a biblioteca styled-components para emotion, isso possibilitou a captura dos estilos no momento em que o SSR é renderizado para inserir no HEAD da página.
