### ISSUE TITLE
Mensagem de sucesso após salvar os dados bancários não aparece ( mas são salvos )

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#1267]
### Contexto

Na interface, por alguma razão os dados do recebedor na página de configurações da comunidade, não estão sendo atualizados após a inserção ou atualização dos dados.

### Exemplo

Faça qualquer alteração de recebedor de uma comunidade e após clicar em salvar, recarregue a página. Verá que os dados não aparecem atualizados no formulário de recebedor.

### Descrição técnica

PR com a correção do problema e se possível adicionar um teste relacionado a esse problema.

### Requisitos e Critérios de Aceite

- [ ] PR no github
- [ ] Aumentar a cobertura

**Comment by vivianedias** [comment]
Fui testar em outro formulário das abas para verificar se ele estava funcionando e nem o de "Informações" que é o primeiro está atualizando.

**Comment by lpirola** [comment]
conseguiu identificar o problema?

**Comment by vivianedias** [comment]
Isso é um problema com:
1. cross storage que nao tava sendo atualizado (nos dois casos, tanto da primeira aba quanto da de recipient)
2. A query do graphql que vem do admin-canary nao estava atualizada

rolou uma ajuda top do @igr-santos nessas

**Comment by vivianedias** [comment]
eu vou criar mais uma issue pra isso, pq o problema nao foi tao trivial e precisa criar uma nova query no hasura. vou arrumar no front e o @igr-santos vai atualizar no hasura

**Comment by lpirola** [comment]
nós não vamos adicionar queries ao hasura no admin, só no admin-canary!

@igr-santos mudamos isso em algum momento?

**Comment by vivianedias** [comment]
é no admin-canary mesmo! quando ele carrega pela primeira vez, ele vem do hasura e depois passa esses dados pro bonde-admin. 

isso acontece no primeiro acesso na comunidade.

**Comment by vivianedias** [comment]
Add teste mesmo sendo no bonde-admin? @lpirola

**Comment by lpirola** [comment]
teste sempre é bom, no admin é ainda melhor pois teremos certeza que o código velho continua funcionando! :)
