### ISSUE TITLE
Add widget direct pressure

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#127]

**Comment by gabrielrtakeda** [comment]
Needs to change text from "Quem você pode pressionar" to "Quem você vai pressionar".

**Comment by gabrielrtakeda** [comment]
Needs to change inputs placeholder:
- "Seu email"
- "Sem nome"
- "Seu sobrenome"

**Comment by gabrielrtakeda** [comment]
Needs to show "pressões feitas" text after count number.

**Comment by gabrielrtakeda** [comment]
It needs to fix targets card when target name is too long.

**Comment by gabrielrtakeda** [comment]
It needs to fix `title_text`, `main_color` and `button_text` default on pressure widget component when save form data on settings. Bug example:

![screen-shot-2016-08-19-at-16 17 1490](https://cloud.githubusercontent.com/assets/5435389/17825161/b2917908-663c-11e6-936e-0c7386a4ccdc.jpg)

**Comment by gabrielrtakeda** [comment]
It needs to change endpoint response object attribute `pressure_count` to `count`.

**Comment by gabrielrtakeda** [comment]
API commit reference: https://github.com/ourcities/hub-api/commit/b19d4b37504fdfc422b9c1bd11d5846204d9a4bf

**Comment by gabrielrtakeda** [comment]
It needs to set an email to targets reply the pressure.

**Comment by gabrielrtakeda** [comment]
It needs to make api call passing data do save and dispatch emails.
