### ISSUE TITLE
Lista de comunidades carrega incompleta quando admin

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#1271]
### Contexto
Após fazer login, no admin canary a lista de comunidades vem sem alguns registros.

**Comment by igr-santos** [comment]
@lpirola a lista de comunidades não está carregando incompleta, os dados de staging é que estão incompletos, de qualquer maneira adicionei uma paginação e tô adicionando um filtro pra ficar mais fácil visualizar as comunidades

**Comment by vivianedias** [comment]
@igr-santos ja terminou essa issue?
