### ISSUE TITLE
[bonde-admin] Nao consigo adc conteudo a um novo bloco criado na edicao das paginas

### ISSUE THREAD

**Issue by vivianedias** [nossas/bonde#1280]
### Contexto

Fluxo que nao esta funcionando:
	- crio novo bloco dentro de uma mobilizaçao 
	- tento editar o bloco -> adc form/pressao/ligacao/etc
	- sou redirecionada para ->  https://admin-canary.staging.bonde.org/admin
	- se tento editar blocos antigos que ja tem algum conteudo, consigo

### Requisitos e Critérios de Aceite

- [ ] Consigo adicionar um bloco e depois editar seu conteudo

**Comment by igr-santos** [comment]
Isso é um problema causado pelas permissões da API-Rest que só funcionam para inserção e atualização com usuários admin, a medida adotada no momento são todos serem admin a fim de manter o funcionamento da API-Rest e criarmos um nível de validação na camada de UX (Admin e Admin Canary)
