### ISSUE TITLE
Enable run tests pre commit

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#129]
https://github.com/Hashnode/mern-starter/blob/master/package.json#L19

https://www.npmjs.com/package/pre-commit

**Comment by gabrielrtakeda** [comment]
# Introduction

Add lint and tests to run before commit.

# Prerequisites
- Needs to install [pre-commit](https://www.npmjs.com/package/pre-commit) package to auxiliate run npm scripts before commits.
- Needs to install and upgrade some packages:

## Upgrade

| package | current | upgrade |
| --- | --- | --- |
| babel-eslint | 4.1.1 | 6.1.2 |
| eslint | 1.3.1 | 2.13.1 |
| eslint-config-airbnb | 0.0.8 | 9.0.1 |
| eslint-plugin-react | 3.3.1 | 5.2.2 |

## Install

| package | version |
| --- | --- |
| eslint-plugin-import | 1.12.0 |
| eslint-plugin-jsx-a11y | 1.5.5 |

**Comment by lpirola** [comment]
We are working in which branch?

**Comment by gabrielrtakeda** [comment]
I didn't pushed the branch yet, my bad 😋
The branch is [lint-on-pre-commit](https://github.com/ourcities/hub-client/tree/lint-on-pre-commit)
I'll push the changes now 🙂

**Comment by gabrielrtakeda** [comment]
Just for packages upgrade reference:
https://github.com/airbnb/javascript/tree/eslint-config-airbnb-v9.0.1/packages/eslint-config-airbnb

**Comment by gabrielrtakeda** [comment]
ESLint configuration docs reference:
http://eslint.org/docs/user-guide/configuring

**Comment by gabrielrtakeda** [comment]
Needs to merge `master` into `lint-on-pre-commit`.

**Comment by gabrielrtakeda** [comment]
Needs to run lint on `.jsx` files.

**Comment by lpirola** [comment]
@gabrielrtakeda after new releases we could add these check more easily?

**Comment by lpirola** [comment]
I will close this issue, since that's is not the behavior we want anymore.
