### ISSUE TITLE
[ canary ] página para convite não carrega para alguns usuários

### ISSUE THREAD

**Issue by igr-santos** [nossas/bonde#1299]
Esse problema foi reportado pela Ana Clara e Leca, foi feita uma primeira analise para entender se o problema era alguma combinação de dados, mas aparentemente os todos esses usuários tem as mesmas configurações de permissão que o meu usuário de teste, usuário que consegue acessar a tabela.

**Comment by lpirola** [comment]
acabei de conversar com a Leca e o problema @igr-santos era que ela acessava a página a partir das configurações do admin e com isso a página ficava em branco.

expliquei o caminho pelo menu de comunidades e agora está funcionando certinho!
