### ISSUE TITLE
Criar biblioteca bonde-core-tools

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#1326]

**Comment by igr-santos** [comment]
Repositório que está sendo desenvolvido:

https://github.com/nossas/bonde-core-tools

Tasks:

- [X] Alterar SessionHOC para novo formato de Hooks do react
- [ ] Adicionar build ao ci x github

Migrar clients para usar sessão do bonde-core-tools
- [ ] https://github.com/nossas/bonde-microservices/pull/182
- [ ] https://github.com/nossas/bonde-client
