### ISSUE TITLE
[ Chatbot ] Cliente versão 0.1 - Possibilitar acesso interno

### ISSUE THREAD

**Issue by igr-santos** [nossas/bonde#1346]
Essa issue tem objetivo de fazer o tracklist de tarefas para implementar uma versão minimamente usual do módulo já existente no admin-canary de chatbot.

Tasks:
- [x] Migrar biblioteca bonde-diagram para tsdx
- [x] Habilitar páginas do módulo chatbot no admin-canary
- [x] Verificar menu URL e lógica de ativação do módulo selecionado

Importante:
- Com a atualização da biblioteca `bonde-diagram` o ambiente de desenvolvimento ficou com um problema descrito na issue: #1347

**Comment by lpirola** [comment]
@igr-santos não é melhor migrar o client do admin-canary para o seu pacote ao invés de integrar com admin-canary?

**Comment by igr-santos** [comment]
@lpirola eu até pensei nisso, mas o build do diagram estava bugado, ia ser mais simples manter as páginas no admin-canary já que lá estavam e corrigir o build do bonde-diagram. Quando tivermos o cliente do chatbot a integração vai ser mais simples. Acho que uma biblioteca precisa de buildar pra funcionar em contexto local e no contexto não local, ou seja o build tem que ser feito da maneira correta, pra evitar dependencias, como configurações por exemplo. Dependencia é um problema grande pra nossa filosofia de desenvolvimento.
