### ISSUE TITLE
Como usuário, gostaria de convidar outros usuários para a comunidade com autonomia

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#1385]

**Comment by igr-santos** [comment]
Alterações no projeto bonde-auth

- Mudança no fluxo para evitar alguns bugs encontrados ao longo do uso do Bonde.
- Adicionadas informações sobre uso da API no README do pacote.
- Adicionado verificação na API e no Client para checar URL de convite antes de continuar o registro.

Além dessas alterações existe um gargalo e uma certa obscuridade na manipulação de notificações por e-mail, irei trabalhar essa melhoria no serviço de notificações sem mudar a lógica para gerar uma notificação, que hoje é feita atráves da criação de um registro na tabela `notify_mail`
