### ISSUE TITLE
Como superusuário, gostaria de poder criar comunidades

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#1389]

**Comment by igr-santos** [comment]
Exemplo de superusuários:

- Leca
- Pirola
- Igor
- Talita
- Viviane

**Comment by igr-santos** [comment]
Algumas anotações feitas a partir de uma call com o @lpirola 
```
- Quem usa a autenticação do Bonde?
- Qual o processo de validação?


- Contexto dos dados (User)
- Granularidade API e Interface (Roles)


1. Criar comunidade (Preencher formulário)
- Proprietário / Criador: Quem criou (provavelmente um responsável do nossas)

- Mobilizadores (Comunidade / Usuário)
  - Funções: Mobilizador, Proprietário

- Mobilizador
  - Criar / Editar mobilização

- Proprietário
  - Herda funções de Mobilizador
  - Pode convidar pessoas
  - Pode configurar Comunidade (Dados sensiveis)

2. Granularidade de acesso aos módulos
- Deve ser configurado a partir do contexto por Comunidade
- Pode existir uma "sub-granularidade" dentro de cada módulo a partir do papel
contido em "comunidade / usuário" para acesso a determinadas funções
```

**Comment by igr-santos** [comment]
As primeiras implementações de permissões já nos dão um panorama de como irão funcionar as futuras validações. Neste momento estou fazendo uma correção no retorno do usuário corrente (usuário logado) ele precisa responder com um atributo que será utilizado para verificar seu status de superusuário, isso é necessário para que os superusuários sejam relacionados as ações do Bonde, já que superusuários na API-GraphQL não possuem tratamente como os usuários comuns, ao qual eu posso diretamente no nível da API fazer uma relação entre os dados do usuário autenticado e a ação, então esse tratamente será feito na parte do cliente apenas para superusuários, com isso eu tenho dominio de queries e mutações que possam ser acessadas por superusuários e fazer a chamada delas apenas quando estes estiverem logados.

**Comment by igr-santos** [comment]
- Adicionar possibilidade de edição por administradores para membros da Comunidade
- Configurar permissões para módulos ativos que usam a API-GraphQL (chatbot, redes)

**Comment by igr-santos** [comment]
- Configurado as permissões para o módulo de Redes, vale acrescentar a falta de histórico para os encaminhamentos, para padronizar a cada nova atualização nos dados de encaminhamentos atualizamos o agente responsável, nesse caso todo agente responsável é aquele usuário que por último atualizou o encaminhamento.

**Comment by igr-santos** [comment]
- Configurado permissões para módulo de Chatbot

**Comment by igr-santos** [comment]
### Done
- Adicionado permissão para Administradores de Comunidade "Remover Mobilizador"
- Adicionado permissão para Administradores de Comunidade "Reenviar convite expirado"

### TODO
- [x] Implementar permissões para Administrador Bonde, Administrador Comunidade e Mobilizador no módulo de Redes

**Comment by igr-santos** [comment]
Fica pendente a edição de funções (Administrador / Mobilizador) no módulo de Mobilizadores, hoje é possível remover o usuário e convidá-lo novamente com a função alterada caso seja de extrema necessidade essa alteração antes da próxima atualização.
