### ISSUE TITLE
Adicionar uma função no bonde-core-tools que retorna dados de geolocalização

### ISSUE THREAD

**Issue by vivianedias** [nossas/bonde#1400]
Ao inserir alguns dados de geolocalização, a função deve retornar uma promessa com lat/lng e mais algumas infos de geolocalizaçao tipo estado e cidade.

Isso está sendo feito no `bonde-core-tools` para que os serviços que estão no `mapa-do-acolhimento` possam usar todos a mesma lógica e não se preocupem em faze-la por lá.

**Comment by igr-santos** [comment]
@vivianedias poderia listar quais os serviços farão uso dessa função, se puder colocar link do github apontando o serviço será interessante também.

**Comment by vivianedias** [comment]
Serviços que usarão essa função:

**mapa-do-acolhimento**
- [listener-solidarity](https://github.com/nossas/mapa-do-acolhimento/tree/main/packages/listener-solidarity)
- [webhooks-mautic-zendesk](https://github.com/nossas/mapa-do-acolhimento/tree/main/packages/webhooks-mautic-zendesk)

**Comment by vivianedias** [comment]
PR `bonde-core-tools`: https://github.com/nossas/bonde-core-tools/pull/3
PR `mapa-do-acolhimento`: https://github.com/nossas/mapa-do-acolhimento/pull/19

**Comment by vivianedias** [comment]
@igr-santos  tem uma branch sua no bonde-core-tools de permissões q nao foi mergeada no main.
Dei pull nela pra prosseguir nas alterações que fiz!
