### ISSUE TITLE
Incluir nas widgets texto sobre consentimento de compartilhamento de dados pessoais

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#1420]

**Comment by igr-santos** [comment]
Texto a ser adicionado:

Ao clicar nesse botão, eu concordo em ter meus dados compartilhados com esta organização para que possam entregar minha assinatura. Aceito receber atualizações de campanha, pesquisas, petições e oportunidades de doação, conforme descrito na política de privacidade. Eu entendo que tenho o direito de cancelar o recebimento desses e-mails a qualquer momento.
