### ISSUE TITLE
Integração contínua (CI/CD)

### ISSUE THREAD

**Issue by igr-santos** [nossas/bonde#1504]
Precisamos discutir sobre a atualização da ferramente de integração contínua, hoje mantemos uma versão do `drone:0.8` devido a uma limitação que passou a existir com a mudança da licença. Texto sobre as mudanças na versão https://laszlo.cloud/drone-community-edition-what-is-included

Existe um projeto que baseia-se na versão que usamos, mas que é mantido pela comunidade, possuindo atualizações e melhorias sem a imposição do limite, esse projeto chama-se [woodpecker](https://github.com/woodpecker-ci/woodpecker).

Atualmente estamos trabalhando a refatoração da plataforma para que tenhamos mais alguns anos de manutenção sobre essa estrutura e a decisão em como usamos o CI irá influenciar bastante no desenvolvimento.

**Comment by igr-santos** [comment]
Uma das opções que podemos utilizar para CI/CD é o Github Actions, após uma breve configuração foi possível fazer a primeira parte do processo que acontecia no Drone.io (tests e build). Outra vantagem é uma extensa documentação em PT-BR o entendimento de uma tecnologia com termos e conceitos bem especificos.

O Github Actions executa seus runners em uma máquina virtual própria, eliminando mais um processo que hoje fica na responsabilidade dos mantenedores, [nesse link](https://docs.github.com/pt/actions/using-github-hosted-runners/about-github-hosted-runners) podemos entender os recursos que estão disponiveis e como disponibilizar nossos recursos em algum caso especifico.

**Comment by gloriateodoro** [comment]
-  Criar branch de trabalho (feature ou hotfix)
- Com as modificações feitas, abrir um PR (caso as modificações não tenham sido finalizadas, criar um PR com a label WIP(work-in-progress))
- Com a contribuição concluída, solicitar um revisor para o PR
- Com a aprovação do PR, fazer o merge da branch para o branch principal

A partir desse processo de contribuição, como podemos automatizar o processo de release de um PR após o merge?

**Comment by igr-santos** [comment]
Acordo semântico de versionamento [SemVer 2.0](https://semver.org/spec/v2.0.0.html)
**Padrão:** `[Major].[Minor].[Patch]`

- Quando a **Major** sobe, isso indica que ouve uma grande mudança, e possível quebra de compatibilidade com as versões anteriores
- Quando a **Minor** sobe, isso indica adição de funcionalidade, sem perda de compatibilidade
- Quando o **Patch** sobe, isso indica correções ou melhorias


Processo Chakra-UI
- PR Workflow: `build`, `tests`, `lint`


BETA
- Tag utilizada para deploy em staging
