### ISSUE TITLE
Monorepo / Codebase

### ISSUE THREAD

**Issue by igr-santos** [nossas/bonde#1508]
Depois de uma discussão sobre build, tests, integração continua, releases e versionamento. Chegamos a conclusão de que podemos agrupar todo o codebase do Bonde em um único repositório (monorepo), centralizando o desenvolvimento e processo, sem centralizar a arquiterura pois essa é distribuida em micro serviços.

Existem 4 principais pontos na plataforma:

- **Clients:** Hoje aplicações [CRA](https://github.com/facebook/create-react-app) ou [SSR](https://nextjs.org/) que são compiladas e então distribuidas em imagem Docker como serviço;
- **Libs:** Bibliotecas com lógicas a serem compartilhadas pelos serviços da plataforma, são compiladas e então distribuidas utilizando [PNPM](https://pnpm.io/motivation) localmente e NPMJS(https://www.npmjs.com/) quando em produção.
- **APIs:** Aplicações NodeJS que integram a API-GraphQL, hoje considerada como Backend tem a responsabilidade de atuar ao lado da base de dados e serviços de integração, são compiladas e distribuidas em imagens Docker como serviço;
- **Workers:** Aplicações NodeJS que executam a partir de um gatilho. Também é considerado como Backend mas são responsáveis por operações mais pontuais e manipulam ou resgatam dados a partir da API-GraphQL, são compilados e então distribuídos em imagem Docker como serviço;

**Comment by igr-santos** [comment]
Casos de uso para **libs**

- **components:** Biblioteca baseada em React + Chackra UI, responsável pelo sistema de componentização de ` clients` BONDE
- **core-tools:** Biblioteca que possui funções para gerenciamento da sessão de usuário, nesse caso compartilhada por `clients`, `apis` e `workers` significando que deve existir nos ambientes `client-side` e `server-side`

**Comment by lpirola** [comment]
Documentação sobre como funciona o modo de biblioteca do vitejs. https://vitejs.dev/guide/build.html#library-mode
