### ISSUE TITLE
Update redux-form version

### ISSUE THREAD

**Issue by igr-santos** [nossas/bonde#154]
# Packages
## 🚀 Updated

| Package | Current version | New version |
| --- | --- | --- |
| autoprefixer | 6.3.6 | 6.4.1 |
| jsdom | 9.4.0 | 9.5.0 |
| newrelic | 1.28.1 | 1.30.1 |
| node-sass | 3.7.0 | 3.9.3 |
| raven-js | 3.2.0 | 3.6.1 |
| react-color | 2.2.2 | 2.2.7 |
| redux | 1.0.1 | 3.5.2 |
| redux-devtools | 1.0.2 | 1.1.2 |
| redux-form | 0.2.1 | 5.3.2 |
| redux-thunk | 0.1.0 | 2.1.0 |
## ✅ New

| Package | Version |
| --- | --- |
| axios | 0.14.0 |
| http-proxy-middleware | 0.17.1 |
## ❌ Removed

| Package | Version | Reason |
| --- | --- | --- |
| http-proxy | 1.13.3 | Migrates to `http-proxy-middleware` |
# Tests
#### W.I.P.
- [x] Empty List (drag your item below)
- [x] Fix tests
# Pages Refactoring

Pages that needs to be refactored and adapted to new version of redux-form:
#### W.I.P.
- [x] Empty List (drag your item below)
- [x] MobilizationSharingPage
- [x] FormWidgetForm
- [x] MobilizationFontsPage
- [x] MobilizationCityPage
- [x] MobilizationBasicsFormPage
- [x] MobilizationCustomDomainPage
- [x] Form/pages/Fields.js
- [x] MobilizationAnalyticsPage
# Migration

It needs to migrate some components to new modularized structure:
#### W.I.P.
- [x] Empty List (drag your item below)
- [x] DonationWidget
# Actions Refactoring
#### W.I.P.
- [x] Empty List (drag your item below)
- [x] actions/AuthActions
- [x] Mobilization/MobilizationActions
- [x] Widget/actions

**Comment by gabrielrtakeda** [comment]
It needs to migrate `<DonationWidget>` to new modularized structure to facilitate the refactoring of Menu view strategy.

**Comment by gabrielrtakeda** [comment]
It needs to add the configuration to accepts branch name convention (`fix/xxxx` | `add/xxx`) to make automated deploy to staging environment by CircleCI.

Forgot commit reference: https://github.com/ourcities/hub-client/commit/0d78c83158b15847e2ef0ef2bf39381c5c733f02

**Comment by lpirola** [comment]
It needs to be fixed. On staging environment it is catching errors when dispatch some actions. Example of pages that dispatch this error are: MobilizationSharePage on save, MobilizationFontsPage on save and MobilizationBasicsFormPage on save.

https://app.getsentry.com/nossas-cidades/usuario-final/issues/154355350/

**Comment by gabrielrtakeda** [comment]
It needs to fix pressure widget initial target blank list.

**Comment by gabrielrtakeda** [comment]
It needs to fix undefined `currentId` when reloads widget settings page.

**Comment by gabrielrtakeda** [comment]
Add to description new version of packages that have updated:

| Package | Current version | New version |
| --- | --- | --- |
| autoprefixer | 6.3.6 | 6.4.1 |
| jsdom | 9.4.0 | 9.5.0 |
| newrelic | 1.28.1 | 1.30.1 |
| node-sass | 3.7.0 | 3.9.3 |
| raven-js | 3.2.0 | 3.6.1 |
