### ISSUE TITLE
Não foi possível centralizar o conteúdo do editor

### ISSUE THREAD

**Issue by igr-santos** [nossas/bonde#231]
PR: #229 Deve ser possível centralizar o conteúdo do editor, texto, imagens, iframe e listas

**Comment by lpirola** [comment]
<script iframe-height="600" iframe-width="100%" iframe-src="https://story.mapme.com/cdf2b07a-e1b0-42a0-8031-0c753f76d064" src="https://hosting.mapme.com/story-embed.js"></script>

**Comment by igr-santos** [comment]
Fix alignment to right d8bed50cc1e15e81804dfa400fcb50287ee17dde
