### ISSUE TITLE
Must be possible to use the editor without crashing the mobilization

### ISSUE THREAD

**Issue by igr-santos** [nossas/bonde#234]
PR: #229

**Comment by igr-santos** [comment]
I tried to create a parser to transform the HTML created by the old editor,  but I couldn't  parse html because it doesn't have a pattern.

**Comment by lpirola** [comment]
Our best user tried to create a mobilization using the new editor and she made two comments:
- when her try to change the font size using keyboard, no visual changes are made;
- when she select an image to upload and click in the button to send, nothing happens; She need to wait until image is upload and be visible in content; She thinks some error ocurred and click into send again several times;
