### ISSUE TITLE
Center multiple images single row (inline)

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#255]
Igor,

we have check this kind of behavior in our early talks about image aligment but after release the new editor users are missing a lot this feature. 

They often try to align multiple inline images to achievement some kind of float images but with center align.

You could see this happening in http://www.amarildosepriscilas.meurio.org.br/ and mobilizations/291

**Comment by igr-santos** [comment]
@lpirola check if stayed better

**Comment by gabrielrtakeda** [comment]
This will be fixed in #274 when editor with slatejs have been integrated into bonde.
