### ISSUE TITLE
Community choice page background with scroll

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde#295]
# Pull Request #289 
When access community choice page and have too much communities to list, when scroll the page, the background image is scrolling with the content.

**Screenshot**
<img width="1677" alt="screen shot 2017-01-12 at 11 18 05" src="https://cloud.githubusercontent.com/assets/5435389/21891337/5b88a3d0-d8b9-11e6-9bac-03e4904f67d5.png">

The background image must be with fixed position whenever if the page have scroll or not.
Needs to fix.

**Comment by lpirola** [comment]
@gabrielrtakeda maybe its better to always insert scroll in container besides turn background fixed.

**Comment by gabrielrtakeda** [comment]
Yep, thanks for the advice @lpirola
