### ISSUE TITLE
Bank Account settings is not loading filled info after page refresh 

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#298]
Pull Request #289

**Comment by igr-santos** [comment]
The error is caused because API response is `500 Internal Server Error`

**Comment by lpirola** [comment]
@igr-santos could you check if it is affecting production?

@luizalbsilva could you investigate whats going on? If you need anything, ask me.

**Comment by igr-santos** [comment]
@lpirola @luizalbsilva The API returned `500 Internal Server Error` because CPF or CNPJ is invalid. In API method `[PUT] /communities/:id` must processing payment system error

**Comment by igr-santos** [comment]
@lpirola The validation can be made in front-end. What do you think?

**Comment by lpirola** [comment]
@igr-santos Its great. The API is returning any message of failure?

**Comment by igr-santos** [comment]
@lpirola the API is not returning a explicit failure, only 500 Internal Server error, maybe because isn't being processed correctly the return of payment gateway
