### ISSUE TITLE
Failure trying to create a template

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#301]
Pull Request #286 

When I try to create a template via menu in mobilization list, my first mob is always selected to be the template.

**Comment by igr-santos** [comment]
@lpirola I didn't make reproduce this bug

**Comment by lpirola** [comment]
Look this screenshots to see how I see only the first mobilization selected when are creating a template.

1. Select the mobilization:
![screenshot from 2017-01-13 17 55 57](https://cloud.githubusercontent.com/assets/14948/21943744/d2e69e40-d9b9-11e6-8229-ee15fbdff39a.png)

2. The mobilization showed as template is not the selected one:
![screenshot from 2017-01-13 17 56 44](https://cloud.githubusercontent.com/assets/14948/21943745/d2e6a2dc-d9b9-11e6-82d1-2d0340f92d65.png)
