### ISSUE TITLE
TypeError: this.container is null

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#302]
Pull Request #286

https://sentry.io/nossas-cidades/rebu-website/issues/204492283/

```
TypeError: this.container is null
  at componentDidMount (./app/modules/widgets/__plugins__/content/components/editor-old.js:25:21)
...
(45 additional frame(s) were not displayed)
```

**Comment by igr-santos** [comment]
@lpirola this issue not fail in PR #286, was fixed in https://github.com/ourcities/rebu-client/blob/add/refactor-modules/app/modules/widgets/__plugins__/content/components/editor-old.js#L26

**Comment by lpirola** [comment]
@igor great!
