### ISSUE TITLE
Editor toolbar display above input field when in smaller screens

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#309]
# Pull Request #308 

![screenshot_20170116_102901](https://cloud.githubusercontent.com/assets/14948/21983125/b9789be2-dbd6-11e6-9186-2d149da43fdb.png)

**Comment by gabrielrtakeda** [comment]
@lpirola Ok, I will check this out.

**Comment by gabrielrtakeda** [comment]
@lpirola, fixed it:

**SS**
<img width="750" alt="screen shot 2017-01-16 at 11 09 59" src="https://cloud.githubusercontent.com/assets/5435389/21984289/66f8258a-dbdc-11e6-9e7f-42a6ac0e3a37.png">

I will close this. If it has another issue related, please reopen it.
