### ISSUE TITLE
Problem to change the title block

### ISSUE THREAD

**Issue by manuellaos** [nossas/bonde#319]
![captura de tela 2017-01-18 as 16 00 58](https://cloud.githubusercontent.com/assets/25207509/22078602/52a21f84-dd97-11e6-8dda-3213d7b272e0.png)

Antes, mudava-se o título do bloco nessa faixinha do print (tinha a imagem de um lápis)

**Comment by lpirola** [comment]
Relato de outro usuário:

> As opções para editar/esconder os botões do menu, que ficam no topo de toda página do Reboo, não estão aparecendo pra mim. Dessa forma, como criei um bloco novo, não consigo alterar seu nome de "Bloco 3" para o que quero.
