### ISSUE TITLE
Install babel plugin to resolve aliases

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde#328]
# Introduction
It needs to install [babel-plugin-module-resolver](https://github.com/tleunen/babel-plugin-module-resolver) to handle aliases created on migration to the new boilerplate.

# Branches
- Working branch (base: [feature-migration](https://github.com/nossas/bonde-client/tree/feature-migration)): [feature-install-babel-plugin-module-resolver](http://github.com/nossas/bonde-client/tree/feature-install-babel-plugin-module-resolver)

# Aliases
The current existing aliases are:

**jest.config.json**
```js
{
  "moduleNameMapper": {
    "^~client(.*)$": "<rootDir>/client$1",
    "^~account(.*)$": "<rootDir>/client/account$1",
    "^~components(.*)$": "<rootDir>/client/components$1",
    "^~community(.*)$": "<rootDir>/client/community$1",
    // Needs to be removed. Do not removed yet, because of dependency 
    // to migrate dashboard/Sidebar to client/components/navigation/sidebar
    "^~dashboard(.*)$": "<rootDir>/client/dashboard$1",
    "^~mobilizations(.*)$": "<rootDir>/client/mobilizations$1",
    "^~utils(.*)$": "<rootDir>/client/utils$1",
    "^~widget-plugins(.*)$": "<rootDir>/client/mobilizations/widgets/__plugins__$1"
  }
}
```

So, it needs to create the following aliases after [babel-plugin-module-resolver](https://github.com/tleunen/babel-plugin-module-resolver) installation:

| alias           | path                                      |
|-----------------|-------------------------------------------|
| ~client         | /client                                   |
| ~account        | /client/account                           |
| ~components     | /client/components                        |
| ~community      | /client/community                         |
| ~dashboard      | /client/dashboard                         |
| ~mobilizations  | /client/mobilizations                     |
| ~utils          | /client/utils                             |
| ~widget-plugins | /client/mobilizations/widgets/\_\_plugins\_\_ |

**Comment by gabrielrtakeda** [comment]
I make some modifications in the 41c9973 that needs to be reverted later. The modifications that I make, allows the render of **CustomDomainPage** with a mocked state. Those modifications have a comment with `@revert` to ease to find which file needs to be fixed.

**Comment by gabrielrtakeda** [comment]
@lpirola and @igr-santos I arrived at a moment that I need to decide how to handle the requests comming from a mobilization public view. Currently the new boilerplate does not handle requests comming from a custom domain and do not know how to behave.

Do you think that is a time to create another issue to working on this?

**Comment by lpirola** [comment]
Exactly. @gabrielrtakeda

**Comment by gabrielrtakeda** [comment]
The goal of current issue I think it's already achieved. The **babel-plugin-module-resolver** is already installed and the aliases are working as expected (:

**Comment by gabrielrtakeda** [comment]
Nice @lpirola. So, I will close this issue and open a pull request to **add/refactor-ssr**
