### ISSUE TITLE
Behaviour to render mobilization public view

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde#330]
# Introduction
It needs to add a strategy to render the mobilization public view when the requests come from a custom domain or a slug and, if it matches with one of those values in existing mobilizations. e.g.

## Custom domain match

**Request header** 
```js
request.headers {
  host: 'www.ourcities.org'
}
```
**Mobilization custom domain (in db)**

| id | name       | slug                     | custom_domain     |
|----|------------|--------------------------|-------------------|
| 85 | Our Cities | 78-nossas-cidades-ingles | www.ourcities.org |

## Slug match

**Request header** 
```js
request.headers {
  host: '78-nossas-cidades-ingles.reboo.org'
}
```
**Mobilization custom domain (in db)**

| id | name       | slug                     | custom_domain     |
|----|------------|--------------------------|-------------------|
| 85 | Our Cities | 78-nossas-cidades-ingles | www.ourcities.org |

## Strategy

If cases above, we must render the `custom-domain-page` with its mobilization public view. Otherwise, we must render the not found page.

# Branches
- Working branch (base: [add/refactor-ssr](http://github.com/nossas/bonde-client/tree/add/refactor-ssr)): [feature-custom-domain-route-strategy](http://github.com/nossas/bonde-client/tree/feature-custom-domain-route-strategy)

**Comment by gabrielrtakeda** [comment]
@lpirola @igr-santos, how we proceed about the routes? On the old boilerplate, we use **app.reboo.org** subdomain to know if the users are accessing Bonde's CMS or slug/custom-domain url mobilization's public view. We keep that behaviour or, we modify it using an alternative app root route like **bonde.org/app**?

**Comment by lpirola** [comment]
@gabrielrtakeda the url will be change in #342

**Comment by gabrielrtakeda** [comment]
@lpirola Ok. So instead to have **app.bonde.org/login** for the login page, now we will have **login.bonde.org**. But after login, how url will behave? In the mobilizations list page for example, where the **path** is on the **/**, the url will still **app.bonde.org/**, or we need to create a new path to mobilizations list page like **bonde.org/mobilizations/list**?

**Comment by gabrielrtakeda** [comment]
For now, I will keep the idea to not have the **app.** subdomain to differs for each of mobilization views and create the correct route names to each page. But, for this, I will open another issue. To solve the current issue, I will add the behaviour to render the mobilization from its custom domain that has configured.
