### ISSUE TITLE
Mobile menu is not working as expected on real mobile phones

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#335]
![image](https://cloud.githubusercontent.com/assets/14948/22440666/adafbbc4-e71b-11e6-939a-b3ed9afbffc6.png)
![image](https://cloud.githubusercontent.com/assets/14948/22440670/b05f4e3e-e71b-11e6-9db3-654f7d84fbb0.png)
![image](https://cloud.githubusercontent.com/assets/14948/22440672/b370ce2c-e71b-11e6-9397-4e950ce7f851.png)

**Comment by gabrielrtakeda** [comment]
Working on branch [hotfix-v0.2.1](http://github.com/nossas/bonde-client/tree/hotfix-v0.2.1) created from master.
