### ISSUE TITLE
When editing mobilizations at Block Navigator, actions stop working after first action was fired

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#336]

**Comment by igr-santos** [comment]
@lpirola We need to refactor as it would work the composition to mobilization, blocks and widget components, that was the problem in the case. Must implement reducers to and remove state of component. I talked to @gabrielrtakeda about it recently

**Comment by igr-santos** [comment]
@lpirola @gabrielrtakeda i started a refactor to render mobilization in remote branch https://github.com/igr-santos/bonde-client/tree/refactor-mobilization-render, not yet finalized but is a fast change

**Comment by lpirola** [comment]
@igr-santos Looks nice, maybe it's better add this to new version?
