### ISSUE TITLE
Migrate pages routes to the new boilerplate routes structure (only mobilization)

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde#348]
# Introduction
It needs to migrate all routes, pages and containers to the new boilerplate routes structure. Including an analysis to "merge" the behaviour of containers to fetch the data of the "children" pages.

# Branches
- Working branch (base: [add/refactor-ssr](https://github.com/nossas/bonde-client/tree/add/refactor-ssr)): [feature-migrate-pages-routes](https://github.com/gabrielrtakeda/bonde-client/tree/feature-migrate-pages-routes)

**Comment by lpirola** [comment]
@gabrielrtakeda this issue only migrate pages and we still need another issue to migrate routes?

**Comment by gabrielrtakeda** [comment]
@lpirola The idea when I create this issue was to migrate at the same time, the routes and the pages. An example of migration that I planned is the following:

```js
// client/mobilizations/routes.js

import { MobilizationDashboardContainer } from '~mobilizations/containers'
import { MobilizationListPage } from '~mobilizations/pages'

<Route component={MobilizationDashboardContainer} onEnter={requiredLogin}>
  <Route path='/' component={MobilizationListPage} />
</Route>
```

The page and container:

```
client/mobilizations // <~ client folder
├── containers
│   ├── index.js
│   └── mobilization-dashboard-container.js // <~ MobilizationDashboardContainer
└── pages
    ├── index.js
    └── mobilization-add-page.js // <~ MobilizationListPage
```

Will be migrated/adapted/refactored to something like:

```
routes/mobilizations // <~ routes folder
├── containers
│   ├── index.js
│   └── mobilization-dashboard-container
│       ├── index.js // This is the configuration file that will be explained after
│       ├── page.js // <~ MobilizationDashboardContainer (pure component that uses mobilizations module components)
│       └── page.connected.js // <~ fetch the data
└── pages
    ├── index.js
    └── mobilization-add-page
        ├── index.js // This is the configuration file that will be explained after
        ├── page.js // <~ MobilizationListPage (pure component that uses mobilizations module components)
        └── page.connected.js // <~ fetch the data
```

**Note**: This is just a brief of how migration will occurs. This is not how exactly the migration of these routes will be done. Maybe the container component will be removed and all the fetches dependency data will be described inside of each page route configuration file. It needs to be analyzed more deeply.

## Splitting component/container responsibility
Here I will explain how the component/container will be "splitted" to distribute the responsibility to each one.

**MobilizationDashboardContainer**

This container have some data that needs to be fetched. So, we will split it into two different files.

One is a file that will carry the responsibility to make the fetch of the data.

**Old container example**
```js
// client/mobilizations/containers/mobilization-dashboard-container.js

import { connect } from 'react-redux'
import * as MobilizationActions from '~mobilizations/action-creators'

class MobilizationDashboardContainer extends Component {
  static fetchData (store) {
    const promises = []
    if (!MobilizationSelectors.isLoaded(store.getState())) {
      const { community: { currentId } } = store.getState()
      promises.push(store.dispatch(asyncFetch(currentId)))
    }
    return Promise.all(promises)
  }
  render () {
    const { children, loading, sidebarProps } = this.props
    if (loading) return <Loading />

    return (
      <Sidebar {...sidebarProps}>
        {children && React.cloneElement(children)}
      </Sidebar>
    )
  }
}
const mapStateToProps = (state, props) => ({
  loading: state.mobilization.loading,
  relationshipId: state.community.currentId,
  sidebarProps: getSidebarProps(state, props)
})
export default connect(mapStateToProps, MobilizationActions)(MobilizationDashboardContainer)
```

The `fetchData` static class method above will turns into a fetch using redial

```js
// routes/mobilizations/containers/mobilization-dashboard-container/page.connected.js

import { connect } from 'react-redux'
import { provideHooks } from 'redial'
import MobilizationDashboardContainer from './page'

const redial = {
  fetch: ({ dispatch, host }) => {
    const { community: { currentId } } = store.getState()
    return dispatch(MobilizationActions.asyncFetch(currentId))
  }
}
const mapStateToProps = (state, props) => ({
  loading: state.mobilization.loading,
  relationshipId: state.community.currentId,
  sidebarProps: getSidebarProps(state, props)
})
export default provideHooks(redial)(connect(mapStateToProps)(MobilizationDashboardContainer))
```

And the component with rendering responsibility will be something like this:

```js
// routes/mobilizations/containers/mobilization-dashboard-container/page.js
import Sidebar from '~components/sidebar'

const MobilizationDashboardContainer = ({ children, loading, sidebarProps }) => {
  return loading ? <Loading /> : (
    <Sidebar {...sidebarProps}>
      {children && React.cloneElement(children)}
    </Sidebar>
  )
}
export default MobilizationDashboardContainer
```

The component/container will be "splitted" into one file following the **foo.connected.js** name convention, that will have all fetching data behaviour and another one with the same name of previous one but without the **.connected**, this will be a stateless component that will receive the data from the previous "connected" component and, only with rendering behaviour.

This split distribute the responsibility of fetching or rendering to each one making more easier to identify which file is the rendering component itself or only for fetching the data.

## Route configuration files
So finally, here will be explained how routes will be "refactored" from react-router component style to plain object (Dynamic Routing) style.

As mentioned on the beginning of this explanation, the react-router component routing style below,

```js
// client/mobilizations/routes.js

import { MobilizationDashboardContainer } from '~mobilizations/containers'
import { MobilizationListPage } from '~mobilizations/pages'

<Route component={MobilizationDashboardContainer} onEnter={requiredLogin}>
  <Route path='/' component={MobilizationListPage} />
</Route>
```

Will turns something like plain objects separated each into its respective configuration file:

```js
// routes/mobilizations/containers/mobilization-dashboard-container/route.js

if (typeof require.ensure !== 'function') require.ensure = (d, c) => c(require)
import { injectAsyncReducer } from '~common/store'

const MobilizationDashboardContainerRoute = store => ({
  getComponents (location, cb) {
    require.ensure([], (require) => {
      injectAsyncReducer(store, 'mobilizations', require('~mobilizations/reducers').default)
      cb(null, require('./page.connected').default)
    })
  }
})

export default MobilizationDashboardContainerRoute
```

## Conclusion
The migration of pages, containers and routes needs to be done together because of the dependency of each one, and making more easier to refact/adapt the code of previous boilerplate to the new.

**Comment by gabrielrtakeda** [comment]
@lpirola What do you think about it? Makes sense? What can be improved?

**Comment by gabrielrtakeda** [comment]
@igr-santos Is it following the structure that we discussed previously?

**Comment by igr-santos** [comment]
@gabrielrtakeda The structure and strategy to refactor makes sense, but I would change nomenclature container component, because this component there has to be relationship with layout and not fetch or map props, this is a function of `*.connected.js` that in this case can stay in routes module.

Egg.:

**components/dashboard.js**
```
const Dashboard = ({ children, ...sidebarProps }) => (
    <Sidebar {...sidebarProps}>
        {props.children}
    </SIdebar>
)

export default Dashboard
```

**routes/{pages|containers}/dashboard.connected.js**
```
...
const redial = {
  fetch: ({ dispatch, host }) => {
    const { community: { currentId } } = store.getState()
    return dispatch(MobilizationActions.asyncFetch(currentId))
  }
}
const mapStateToProps = (state, props) => ({
  loading: state.mobilization.loading,
  relationshipId: state.community.currentId,
  sidebarProps: getSidebarProps(state, props)
})
export default provideHooks(redial)(connect(mapStateToProps)(Dashboard))
```

Did you get it?!

**Comment by gabrielrtakeda** [comment]
Nice @igr-santos! I will refact the containers in that way, thanks (:

**Comment by gabrielrtakeda** [comment]
Guys, finally I got to render the mobilization list page with dynamic routes of new boilerplate but, the css of the page is a mess. Follow the screenshot:

<img width="1675" alt="screen shot 2017-02-03 at 10 23 50" src="https://cloud.githubusercontent.com/assets/5435389/22591346/40861bf0-e9fb-11e6-9d3a-5237a56a3e0c.png">

I will keep on track to migrate the pages, containers and routes to have more pages rendered but, after, maybe I will need some help to fix the css of the pages.

**Comment by gabrielrtakeda** [comment]
The last commit (4510013) contains some "mocking" changes that have a `// @revert` comment marked to revert those changes and some explanation about how it could be reverted.

**Comment by gabrielrtakeda** [comment]
# Migration docs
Here will be described which component/container have migrated to which new location, component/container name, etc..

**Note**: All `index.js` files are the route configuration file.

# Naming convention
| name                            | description                             |
|---------------------------------|-----------------------------------------|
| `{page|container}`.connected.js | Inject dependency data to the component |
| `{page|container}`.js           | Pure component rendering                |
| index.js                        | Route configuration file                |

# Containers and Pages

### MobilizationDashboardContainer
The `client/mobilizations/containers/mobilization-dashboard-container` have migrated to:

```
routes
└── authenticated
    ├── container.connected.js
    ├── container.js
    └── index.js
```

### MobilizationListPage
The `client/mobilizations/pages/mobilization-list-page` have migrated to:

```
routes
└── authenticated
    └── mobilizations
        └── list
            ├── index.js
            ├── page.connected.js
            └── page.js
```

### MobilizationAddContainer
The `client/mobilizations/containers/mobilization-add-container` have migrated to:

```
routes
└── authenticated
    └── mobilizations
        ├── container.js
        └── index.js
```

### MobilizationAddPage
The `client/mobilizations/pages/mobilization-add-page` have migrated to:

```
routes
└── authenticated
    └── mobilizations
        └── new
            ├── index.js
            ├── page.connected.js
            └── page.js
```

**Comment by gabrielrtakeda** [comment]
As the migration is growing, it needs that the above comment be updated constantly to centralize the doc of migration.

**Comment by gabrielrtakeda** [comment]
As discussed in a call, I will downgrade the **redux-form**  from **v6.2.0** to version of used in previous boilerplate **v5.3.2** to avoid the refactoring of all forms that uses **redux-form**.
