### ISSUE TITLE
Refactor and Reorganize reducers from Mobilization, Block and Widget

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#356]

**Comment by igr-santos** [comment]
@lpirola @gabrielrtakeda What do you think about this new method of config a widget? https://github.com/igr-santos/bonde-client/commit/a212225705c1cd22c3ee10b569d50dc9e0b21ba9

**Comment by gabrielrtakeda** [comment]
@igr-santos Awesome! I think the idea of a configuration file with all of "dependencies" of each widget was very good! Congratulations for the great work!

**Comment by gabrielrtakeda** [comment]
@igr-santos You can reference this PR or the working issue in your commits, to appear all commits here or in the issue, even if your working branch is on your fork repo.

**Comment by igr-santos** [comment]
Fixed in #391
