### ISSUE TITLE
Merge master into release-v0.4.0

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#363]

**Comment by lpirola** [comment]
Merge done with this commit. Webpack are building with svg and fonts.

https://github.com/nossas/bonde-client/commit/2439c052cb49dcfcf245f99bf23e29f2c160d48e

**Comment by gabrielrtakeda** [comment]
@lpirola You made a `git merge`? Maybe `git rebase` should be a better idea because the branch **add/refactor-ssr** is based on branch **master**. I `git pull` it locally and some files and modules have been returned back into **.old/** directory:

e.g.
```
.old/app/components
├── EmptyList
│   ├── EmptyList.js
│   └── EmptyList.spec.js
├── FilterableSearchBar
│   └── index.js
├── Navigation
│   ├── Sidenav
│   │   └── Sidenav.js
│   └── Tabs
│       ├── Tab.jsx
│       └── __tests__
│           └── Tab.spec.js
└── SelectableList
    ├── SelectableList.js
    └── index.js
```

```
.old/app/modules
├── account
├── community
├── mobilizations
└── widgets
```
