### ISSUE TITLE
 Migrate pages routes from blocks and widgets

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#368]
# Widget plugins routes
- block - 1 route
    - [x] `/mobilizations/:mobilization_id/blocks/create`
- donations - 2 routes
    - [x] `/mobilizations/:mobilization_id/widgets/:widget_id/donation`
    - [x] `/mobilizations/:mobilization_id/widgets/:widget_id/donation/finish`
- form_entries - 3 routes
    - [x] `/mobilizations/:mobilization_id/widgets/:widget_id/form`
    - [x] `/mobilizations/:mobilization_id/widgets/:widget_id/form/fields`
    - [x] `/mobilizations/:mobilization_id/widgets/:widget_id/form/finish`
- pressure - 3 routes
    - [x] `/mobilizations/:mobilization_id/widgets/:widget_id/pressure`
    - [x] `/mobilizations/:mobilization_id/widgets/:widget_id/pressure/email`
    - [x] `/mobilizations/:mobilization_id/widgets/:widget_id/pressure/finish`

# Widget common routes
Remove upper route to set menu in each connected page
- auto fire - 1 upper route
    - [x] `/mobilizations/:mobilization_id/widgets/:widget_id/donation/autofire`
    - [x] `/mobilizations/:mobilization_id/widgets/:widget_id/form/autofire`
    - [x] `/mobilizations/:mobilization_id/widgets/:widget_id/pressure/autofire`
- export data - 1 upper route 
    - [x] `/mobilizations/:mobilization_id/widgets/:widget_id/donation/export`
    - [x] `/mobilizations/:mobilization_id/widgets/:widget_id/form/export`

# Removing the barbs
- [x] Remove unused files like containers that are already migrated, routes files, etc...
- [x] Patternize components name and coding style
- [x] Create tests to pages/components that do not have yet (only validates the render)

**Comment by gabrielrtakeda** [comment]
# Routes path change
I will need to change some routes path. The first route path that I need to change is `/blocks/create` to `/mobilizations/:mobilization_id/blocks/create`. This change is necessary when this route is accessed directly from url (i.e. without navigation). If this route is accessed directly, we cannot identify for which mobilization the block needs to be created. So, the `:mobilization_id` params are required.

### Files organization tree
The route path `/mobilizations/:mobilization_id/blocks/create` will be abbreviated to **blocks-create** route folder as below:

```
routes
└── application
    └── blocks-create
        ├── index.js
        ├── page.connected.js
        ├── page.js
        └── page.scss
```
