### ISSUE TITLE
Review webpack production config

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#369]

**Comment by lpirola** [comment]
As our build still broke I investigate a bit and found this: https://github.com/facebook/jest/issues/2179#issuecomment-268609264

I will try to add more memory to circleci or disable codecoverage. @gabrielrtakeda

**Comment by lpirola** [comment]
Possible solutions:

https://github.com/tmpvar/jsdom/issues/1682#issuecomment-276774388

**Comment by gabrielrtakeda** [comment]
@lpirola As discussed, we do not use the `jsdom` with Jest.. What I suspect is maybe something related with some babel configuration that overheading the memory or something about..

If any of these solutions does not solves our problem with Jest, maybe try to run the tests in "chunks" by module is a way to go.. Or not.. Just a suggestion..

**Comment by gabrielrtakeda** [comment]
Once, I tried to run tests with the following command:

```
node --max_old_space_size=4096 --optimize_for_size --max_executable_size=4096 --stack_size=4096 /usr/local/bin/yarn test
```

But, I do not tested in staging.. I make some googling about the error: `FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory`

And the command above was one of the solutions..

**Comment by lpirola** [comment]
I will close this issue, since the error is gone.
