### ISSUE TITLE
View not changing on login error

### ISSUE THREAD

**Issue by luizalbsilva** [nossas/bonde#372]
If you use an invalid user/password, and login fails, the view is not notifying the user.

**Comment by luizalbsilva** [comment]
Zendesk #191

**Comment by manuellaos** [comment]
You mean this? 

![captura de tela 2017-02-14 as 13 09 11](https://cloud.githubusercontent.com/assets/25207509/22937258/d4e39002-f2b6-11e6-9906-30f672286a89.png)

**Comment by lpirola** [comment]
@manuellaos could you check this again? Maybe you could move the message outside from that box and bg will be black. Got it?

**Comment by gabrielrtakeda** [comment]
It needs to fix this with new boilerplate.
