### ISSUE TITLE
Add reference to link to bonde at footer

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#389]

**Comment by lpirola** [comment]
@gabrielrtakeda yout could set something like ```?utm_source=logo-footer```

**Comment by gabrielrtakeda** [comment]
Yep @lpirola, I'll do that (:

**Comment by gabrielrtakeda** [comment]
@lpirola, I will put the following `utm_source` tracking values, what do you think?

| **CTA**                                                                                                                                                                  | **utm_source**              |
|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------|
| <img width="95" alt="screen shot 2017-03-21 at 10 17 30 pm" src="https://cloud.githubusercontent.com/assets/5435389/24177926/6bd7834a-0e84-11e7-9ec1-27afefe549a1.png">  | `?utm_source=footer-logo`   |
| <img width="298" alt="screen shot 2017-03-21 at 10 17 24 pm" src="https://cloud.githubusercontent.com/assets/5435389/24177935/816431a4-0e84-11e7-8ac8-89c2a55bffcc.png"> | `?utm_source=footer-slogan` |

**Comment by gabrielrtakeda** [comment]
Both are a link to http://www.bonde.org/
