### ISSUE TITLE
PWA predeploy: Removing the barbs

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde#411]
# Introduction
List of bugs that must be fixed before deploy

## Layout
- [x] Font Family difference in comparison with current production app. In production the font family used is `font-family: 'Source Sans Pro', 'Proxima Nova', sans-serif;` (Maybe in staging the fonts **Source Sans Pro** and **Proxima Nova** does not found and it uses **sans-serif**)

| **Staging**                                                                                                                                                             | **Production**                                                                                                                                                          |
|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------:|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------:|
| <img width="679" alt="screen shot 2017-03-09 at 2 03 37 pm" src="https://cloud.githubusercontent.com/assets/5435389/23761440/947fae06-04d1-11e7-8ce4-ad309a7cc2bb.png"> | <img width="678" alt="screen shot 2017-03-09 at 2 03 54 pm" src="https://cloud.githubusercontent.com/assets/5435389/23761513/c9768f62-04d1-11e7-9c7c-fa1590832b4e.png"> |

- [x] Mobilization list item cell horizontal and vertical alignments

| **Staging**                                                                                                                                                              | **Production**                                                                                                                                                           |
|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|
| <img width="1524" alt="screen shot 2017-03-09 at 2 11 11 pm" src="https://cloud.githubusercontent.com/assets/5435389/23761701/687d0afa-04d2-11e7-9c88-67e6db8783b2.png"> | <img width="1524" alt="screen shot 2017-03-09 at 2 11 35 pm" src="https://cloud.githubusercontent.com/assets/5435389/23761699/685fba68-04d2-11e7-80cf-3bcace5df62e.png"> |

- [x] Mobilization list item menu layout and click show on click. In the staging, the menu is opening on hover, the right behaviour to show is on click.
    - [x] The same in templates list. Solving one, it should reflect to another.

| **Staging**                                                                                                                                                             | **Production**                                                                                                                                                          |
|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------:|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------:|
| <img width="447" alt="screen shot 2017-03-09 at 2 14 21 pm" src="https://cloud.githubusercontent.com/assets/5435389/23761811/cf327046-04d2-11e7-943b-c39379109160.png"> | <img width="446" alt="screen shot 2017-03-09 at 2 14 36 pm" src="https://cloud.githubusercontent.com/assets/5435389/23761810/cf17b224-04d2-11e7-8093-df35d873afad.png"> |

- [x] Sidebar community logo loads right in SSR but when client code loads, the logo image is override with Bonde Logo

| **SSR**                                                                                                                                                                | **Client**                                                                                                                                                             |
|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------:|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------:|
| <img width="92" alt="screen shot 2017-03-09 at 2 40 37 pm" src="https://cloud.githubusercontent.com/assets/5435389/23762971/a5b88e2c-04d6-11e7-913a-36a20470c511.png"> | <img width="93" alt="screen shot 2017-03-09 at 2 40 42 pm" src="https://cloud.githubusercontent.com/assets/5435389/23762970/a5ae3f3a-04d6-11e7-82e9-50ad257267ee.png"> |

- Choose community page
    - [x] Background image does not loading
    - [x] Communities list layout is broken

| **Staging**                                                                                                                                                              | **Production**                                                                                                                                                           |
|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|
| <img width="1671" alt="screen shot 2017-03-09 at 3 16 01 pm" src="https://cloud.githubusercontent.com/assets/5435389/23764254/a871665c-04db-11e7-9634-5ee488a5d7af.png"> | <img width="1666" alt="screen shot 2017-03-09 at 3 15 46 pm" src="https://cloud.githubusercontent.com/assets/5435389/23764253/a86fdd82-04db-11e7-9ab8-f196022c0b20.png"> |

- Create community page
    - [x] Background image does not loading
    - [x] Create community form layout is broken

| **Staging**                                                                                                                                                              | **Production**                                                                                                                                                           |
|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|
| <img width="1674" alt="screen shot 2017-03-09 at 3 20 04 pm" src="https://cloud.githubusercontent.com/assets/5435389/23764357/01d9e93a-04dc-11e7-84fa-eb29704ad4af.png"> | <img width="1670" alt="screen shot 2017-03-09 at 3 19 56 pm" src="https://cloud.githubusercontent.com/assets/5435389/23764358/01f9b4ae-04dc-11e7-94ec-f07907b5f8a8.png"> |

- [x] Align vertically the template list item date cell in choose template page on create mobilization flow http://reboo-staging.org/mobilizations/376/templates/choose/custom

<img width="787" alt="screen shot 2017-03-09 at 4 15 51 pm" src="https://cloud.githubusercontent.com/assets/5435389/23766979/97f3d990-04e5-11e7-8731-a67f1f99d9a8.png">

## Front/Server Side
- [x] An error is dispatched when save the recipient form
http://reboo-staging.org/community/recipient
```
PUT http://api-ssl.reboo-staging.org/communities/1 500 (Internal Server Error)
```

- [x] Remove mocked **current community id** from community reducers to make possible to choose another community in http://reboo-staging.org/community

## DevOps
- [x] Redux DevTools is loading on staging that the build env var is production

<img width="424" alt="screen shot 2017-03-09 at 2 46 01 pm" src="https://cloud.githubusercontent.com/assets/5435389/23763393/2a753402-04d8-11e7-997c-e5d14e899a3b.png">

**Comment by igr-santos** [comment]
Some problems with Community pages can't be fixed without first fix the flow and remove dummy data like user authenticate and community selected

**Comment by gabrielrtakeda** [comment]
>Some problems with Community pages can't be fixed without first fix the flow and remove dummy data like user authenticate and community selected

@igr-santos About the data of the community, mocked in `client/community/reducers.js` like:
```
const initialState = {
  isLoaded: true,
  data: [],
  // @revert To undefined
  currentId: 9
}
```

The `currentId` is required on the **mobilization list page** that is our current root route defined in `routes/logged-in/sidebar/index.js`:
```
  path: '/',
  getIndexRoute (location, cb) {
    require.ensure([], (require) => {
      cb(null, {
        component: require('./mobilizations-list/page.connected').default
      })
    })
  },
```

We can define the root route to **community list page** (route: `/community`, file: `routes/logged-in/background/community-list/index.js`) taking into consideration that we have a valid authentication data mocked in `authenticate/redux/reducer.js` we can list all the communities associated to that **mocked user**.

With this, we remove the dependency of the mocked community data.

**Comment by igr-santos** [comment]
@gabrielrtakeda I'm working on remove mocked data, but in community case will be need change flow of fetch and selection.

**Comment by gabrielrtakeda** [comment]
But we have the auth data, we can fetch the mobilization list only with the auth mock data:

e.g.
```bash
curl -v \
  -X GET \
  -H 'Content-Type: application/json' \
  -H 'access-token: (_____)' \
  -H 'token-type: (_____)' \
  -H 'client: (_____)' \
  -H 'expiry: (_____)' \
  -H 'uid: (_____)' \
  http://localhost:3000/communities | python -m json.tool
```

With is, we were able to remove the mocked community data and, when the user choose the community, the `currentId` in the community reducers will be filled.

But it does not necessarily a requirement. It only advance a step when the @lpirola finish the authentication (**login**) steps. When the authentication steps are done, it becomes a requirement.
