### ISSUE TITLE
Fix create block page form submit

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde#437]
# Introduction
It needs to fix the following error after submit create block form:

- [ ] Error after form submit
<img width="551" alt="screen shot 2017-03-16 at 2 01 44 am" src="https://cloud.githubusercontent.com/assets/5435389/23982487/8d31a8dc-09ec-11e7-9408-c008d7880c11.png">

- [x] It seems like that the request to API is dispatching. After reload the page, the block was created. But without default background color.

# URL
- http://reboo-staging.org/mobilizations/397/blocks/create

**Comment by igr-santos** [comment]
@gabrielrtakeda The error after form submit happened because the API Server should return the widgets inserted in endpoint `[POST] /mobilizations/{mobilization_id}/blocks`

**Comment by gabrielrtakeda** [comment]
@igr-santos So the staging API does not using the correct version?

**Comment by igr-santos** [comment]
@gabrielrtakeda i think that the problem it is on branch `feature-add-widgets-to-block` on `bonde-server`

**Comment by gabrielrtakeda** [comment]
Oh! I thought that staging API was on the correct branch 😞 
So could you push the right branch to staging API and test if the error gone?

**Comment by igr-santos** [comment]
But in my environment, i use this branch and didn't work, I comment with @luizalbsilva  and I will wait a him response

**Comment by gabrielrtakeda** [comment]
@igr-santos Ok
