### ISSUE TITLE
Community recipient form submit

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde#443]
# Introduction
When update the recipient data and submit the form, the following error was dispatched on browser console:

<img width="711" alt="screen shot 2017-03-16 at 2 53 24 am" src="https://cloud.githubusercontent.com/assets/5435389/23983603/c1acd4fe-09f3-11e7-8d31-1b66faf71da1.png">

But the sentry catch an exception on API:
https://sentry.io/nossas-cidades/staging-rebu-api-server/issues/235559759/

**Error PagarMe::ValidationError - Exception**
```
RestClient::BadRequest: 400 Bad Request
  app/services/transfer_service.rb:100:in `register_recipient'
    PagarMe::Recipient.create( recipient_data )
  app/controllers/communities_controller.rb:111:in `recipients'
    recipient = (TransferService.register_recipient recipient_data)
  app/controllers/communities_controller.rb:42:in `block in update'
    recipients community, recipient_data
  app/controllers/communities_controller.rb:39:in `update'
    Community.transaction do
...
(102 additional frame(s) were not displayed)

PagarMe::ValidationError: Value out of range, maximum allowed value is 5
  app/services/transfer_service.rb:100:in `register_recipient'
    PagarMe::Recipient.create( recipient_data )
  app/controllers/communities_controller.rb:111:in `recipients'
    recipient = (TransferService.register_recipient recipient_data)
  app/controllers/communities_controller.rb:42:in `block in update'
    recipients community, recipient_data
  app/controllers/communities_controller.rb:39:in `update'
    Community.transaction do
...
(95 additional frame(s) were not displayed)
```

# URL
- http://reboo-staging.org/community/recipient

**Comment by igr-santos** [comment]
@gabrielrtakeda in recipient form, exists a validation for inputs, in my environment this validation block the request, wich information do you used to fill the fields?

**Comment by gabrielrtakeda** [comment]
@igr-santos Maybe this is not a bug, when I was testing this in staging, I was updating the CPF and, this change is not allowed by default by API, because of some business rules of Pagar.me..

I will send the environment variables that I use in my local API in slack. Can you test this form without change the documents (CPF of RG I really do not remember) and post a feedback, please?

**Comment by lpirola** [comment]
@gabrielrtakeda I just test this again and found the same bug. Maybe is something with not correct use of pagarme security keys. If you look at api logs nothing appears.
