### ISSUE TITLE
Default editor as slate-editor

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde#446]
# Introduction
It needs to investigate why the new mobilizations are creating content widgets with **Draft.js** editor implementation instead of **SlateJS** editor.

**When the content widget appears with the blue borders it is because the Draft.js editor is loaded instead of SlateJS editor**

<img width="920" alt="screen shot 2017-03-16 at 3 16 45 am" src="https://cloud.githubusercontent.com/assets/5435389/23984215/1b947186-09f7-11e7-90e7-5ce866517011.png">

# URL
- http://reboo-staging.org/mobilizations/399/edit

**Comment by igr-santos** [comment]
Fix commit https://github.com/nossas/bonde-client/commit/bd6c2242266bc1b87e1c8535f95b581de1691829

**Comment by igr-santos** [comment]
Is need fix toolbar layout.
