### ISSUE TITLE
Undefined Editor of wysihtml5

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde#454]
# Introduction
It needs to fix the **wysihtml5** lib import when try to edit the content of content wdget. Follow the error:

```
TypeError: Cannot read property 'Editor' of undefined
    at EditorOld.componentDidMount (editor-old.js:66)
    at eval (ReactCompositeComponent.js:265)
    at measureLifeCyclePerf (ReactCompositeComponent.js:75)
    at eval (ReactCompositeComponent.js:264)
    at CallbackQueue.notifyAll (CallbackQueue.js:76)
    at ReactReconcileTransaction.close (ReactReconcileTransaction.js:80)
    at ReactReconcileTransaction.closeAll (Transaction.js:206)
    at ReactReconcileTransaction.perform (Transaction.js:153)
    at ReactUpdatesFlushTransaction.perform (Transaction.js:140)
    at ReactUpdatesFlushTransaction.perform (ReactUpdates.js:89)
```

**Comment by gabrielrtakeda** [comment]
@lpirola About this error, I dive into the commits and I found this commit 4f617e726b68c53c37321c90fe6820b8770326b0 in specific that the **wisyhtml5** lib was removed from **server/index.js** file and moved to **package.json** as a module dependency.

But, in the **client/mobilizations/widgets/__plugins__/content/components/wysihtml-advanced.js**  file, the first line `import wysihtml5 from 'wysihtml/src/wysihtml5'` it may be wrong because, if we follow the folder into **node_modules/wysihtml/src/wysihtml5.js** file, it doest not **export** the variable.

**Content of node_modules/wysihtml/src/wysihtml5.js**
https://github.com/Voog/wysihtml/blob/0.5.2/src/wysihtml5.js

What do you think about this? It makes sense or I misunderstanding?

**Comment by gabrielrtakeda** [comment]
I think for the use of the **wysihtml5** editor library, we have three options:

1. Upgrade the **wysihtml5** editor library to the latest version to try if it have some **"exports"** strategies;
2. Fork the **Voog/wysihtml** repository and make the necessary **"exports"** to make it works as a npm module. 
3. Regress to import **wysihtml5** editor library inside html tag directly as it was made before.

Maybe it have one more option that we include a `script-loader` into webpack configuration to make the "download" of the CDN minified code and include it into the bundle. But honestly, I do not know how to do it exactly..

**Comment by lpirola** [comment]
@gabrielrtakeda maybe we could try to import the editor too, what do you think? I guess that this problem with export should have not was a problem.

**Comment by lpirola** [comment]
Do you have the command to dump db without pg_dump? To try this local, I must have the old data.

**Comment by gabrielrtakeda** [comment]
@lpirola Unfortunately I only have the dump command using `pg_dump` 😕

**Comment by gabrielrtakeda** [comment]
@lpirola You do not necessarily needs the latest version of db to test the editor implementation with **wysihtml5** library.. You can query in db for content widgets that have its content with html, follow the query to get mobilizations that contains the content widget using **wysihtml5** editor:

```sql
select distinct m.custom_domain from widgets as w
right join blocks as b on b.id = w.block_id
right join mobilizations as m on m.id = b.mobilization_id
where w.settings -> 'content' like '<%';
```

You can get one of those `custom_domain`s and put it into your **/etc/hosts** pointing to your localhost.

**Comment by gabrielrtakeda** [comment]
It is being very difficult to bundle the `wysihtml` lib with webpack. For now, I will revert to load the `wysihtml` as a script inside **server/index.js** to make the mobilizations that uses content widget with **wysihtml** editor work again.

**Comment by lpirola** [comment]
https://github.com/Voog/wysihtml/issues/374 :joy:

**Comment by lpirola** [comment]
@gabrielrtakeda after revert change to import  wyshtml module from package, the following error appear.

```
Uncaught (in promise) Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.
    at invariant (invariant.js:44)
    at instantiateReactComponent (instantiateReactComponent.js:77)
    at instantiateChild (ReactChildReconciler.js:44)
    at eval (ReactChildReconciler.js:71)
    at traverseAllChildrenImpl (traverseAllChildren.js:77)
    at traverseAllChildrenImpl (traverseAllChildren.js:93)
    at traverseAllChildren (traverseAllChildren.js:172)
    at Object.instantiateChildren (ReactChildReconciler.js:70)
    at ReactDOMComponent._reconcilerInstantiateChildren (ReactMultiChild.js:187)
    at ReactDOMComponent.mountChildren (ReactMultiChild.js:226)
```

**Comment by lpirola** [comment]
Fixed rolling back load file from script tag as suggest from @gabrielrtakeda
