### ISSUE TITLE
Replace process.env.BROWSER to exenv lib

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde#458]
# Introduction
It seems that the `process.env.BROWSER` variable is does not working.. In replacement of this node environment variable, we should use the [exenv](https://github.com/JedWatson/exenv) library

**Comment by lpirola** [comment]
@gabrielrtakeda did you think we could remove use of ```ìf (process.env.BROWSER) {``` to load css and imagens?

**Comment by gabrielrtakeda** [comment]
@lpirola Yep, exactly! I tested the use of `exenv` in 3d04002b0c1aab987eee61ec3bce147bfc53a9a9 and it works like a charm!
