### ISSUE TITLE
Fail when try to donate in mobilization

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#467]
In the following mobilization http://302-teste-geral.reboo-staging.org/ the request to API after finish donation was not fired.

**Comment by igr-santos** [comment]
@lpirola I can't reproduce this error when I do the test, i did a test with a dummy credit card.

Exists in this mobilization other donation widget, like it hasn't payment informations and without this informations we can't donate, how should I solve this problem?

**Comment by lpirola** [comment]
@igr-santos Did you try in staging? You receive a http status code 200 from API when donation is done?

**Comment by igr-santos** [comment]
@lpirola Yes, i do.

I receive status code 200 in donation recurrent and donation unique, i didn't have problems. Show me your donation step-by-step for better understand.

**Comment by lpirola** [comment]
@igr-santos as we talked about this, the main problem is that our API don't receive any data after donation is done.
