### ISSUE TITLE
Missing zendesk button

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#468]

**Comment by gabrielrtakeda** [comment]
@lpirola It dispatches an error? Sometimes in my development environment the display of zendesk widget is intermittent.

**Comment by gabrielrtakeda** [comment]
The zendesk widget does not displaying in staging because the `NODE_ENV` is production. In React, the `<script />` tag is removed by default. May it needs to do some workaround like this: http://stackoverflow.com/questions/34424845/adding-script-tag-to-react-jsx
