### ISSUE TITLE
Wierd scroll to top after first load from mobilization

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#478]
Occurs with http://342-cpi-da-violencia-contra-a-mulher.reboo-staging.org/, call me at slack and I could add more details. It's very annoying this bug.

**Comment by lpirola** [comment]
New bug found related to this, any link with hash to on of block are not working.

**Comment by lpirola** [comment]
Remove touchstart listeners

**Comment by gabrielrtakeda** [comment]
When access a mobilization url that contains a hash that jump to a content

![apr-19-2017 14-10-57](https://cloud.githubusercontent.com/assets/5435389/25192607/35a36df6-250a-11e7-855a-e75432f4833c.gif)

**Comment by gabrielrtakeda** [comment]
In conversation with a community member of `react-router` in [reactiflux discord server](https://discord.gg/0ZcbPKXt5bYaNQ46) to understands how to solve this, I was suggested to use the [react-router-scroll](https://github.com/taion/react-router-scroll) package to try to handle the scroll via hash on the client bundle or, in a more low level solution, to handle using the `scrollIntoView` in the callback to `ReactDOM.render` follow the example code below:

```js
ReactDOM.render(
  <Router history={browserHistory}>...</Router>,
  document.getElementById('root'),
  () => {
    // this might be the incorrect way to get the current location
    if (browserHistory.location.hash) {
      const element = document.querySelector(browser.location.hash);
      if (element) {
        element.scrollIntoView();
      }
    }
  }
);
```
