### ISSUE TITLE
Not required xhr request on every page to false endpoint

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#479]
http://342-cpi-da-violencia-contra-a-mulher.reboo-staging.org/false

**Comment by igr-santos** [comment]
I can't reproduce this error. I did test in local and staging environment.

**Comment by lpirola** [comment]
@igr-santos try to find ```src="false"``` in source code generated to this mobilization. An image is responsible to do the request. Looks like is something in editor v2.

**Comment by gabrielrtakeda** [comment]
May this https://github.com/nossas/bonde-client/blob/release-v0.4/client/mobrender/components/mobilization.js#L75 is causing the `false` on image src attr

**Comment by gabrielrtakeda** [comment]
Putting a ternary operator with `null` in else condition may solves.
