### ISSUE TITLE
New editor not change font size

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#484]

**Comment by igr-santos** [comment]
This behavior is pattern, because the fontSize is changed only when <Enter> is pressed, see this code https://github.com/nossas/slate-editor/blob/master/src/package/plugins/slate-font-size-plugin/FontSizeInput.js#L31, do we should change this behavior?

**Comment by lpirola** [comment]
@igr-santos hummm, I guess will be better if we could see visual changes on every number change. It's possible?

**Comment by gabrielrtakeda** [comment]
nossas/slate-editor#2

**Comment by gabrielrtakeda** [comment]
@lpirola You can use the keyboard shortcut to increase or decrease the font size. The behaviour will be the same..
