### ISSUE TITLE
Add back button when creating mobilization with template

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#485]
After choose to global templates or local templates we can't go back.

URL Ref: http://reboo-staging.org/mobilizations/409/templates/choose/global

**Comment by gabrielrtakeda** [comment]
@lpirola This is the flow?

| **new mobilization**                                                                                                                                                    | **template strategy**                                                                                                                                                   | **choose template**                                                                                                                                                     |
|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| <img width="828" alt="screen shot 2017-03-22 at 2 02 12 pm" src="https://cloud.githubusercontent.com/assets/5435389/24210600/61b9a062-0f08-11e7-9c3d-9d2f081644be.png"> | <img width="790" alt="screen shot 2017-03-22 at 2 02 42 pm" src="https://cloud.githubusercontent.com/assets/5435389/24210598/61b5f3ea-0f08-11e7-93f5-2e2be58ad132.png"> | <img width="779" alt="screen shot 2017-03-22 at 2 02 50 pm" src="https://cloud.githubusercontent.com/assets/5435389/24210599/61b673d8-0f08-11e7-9fa8-6e52cc45fc75.png"> |

You want to add a back button into **choose template** step?

**Comment by igr-santos** [comment]
I am working this is issue

**Comment by gabrielrtakeda** [comment]
Great @igr-santos!
