### ISSUE TITLE
Add option to set text to set whatsapp text share

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#487]

**Comment by gabrielrtakeda** [comment]
**Routes**
- `/mobilizations/:mobilization_id/widgets/:widget_id/form/finish`
- `/mobilizations/:mobilization_id/widgets/:widget_id/donation/finish`
- `/mobilizations/:mobilization_id/widgets/:widget_id/pressure/finish`

**Solution**

<img width="1154" alt="screen shot 2017-03-29 at 9 27 33 pm" src="https://cloud.githubusercontent.com/assets/5435389/24482319/b002594e-14c6-11e7-91d6-132a37a1a588.png">

**Comment by gabrielrtakeda** [comment]
Before this feature go to live, it needs to nossas/bonde-server#217 be merged.
