### ISSUE TITLE
Reorganize tests to meet new tree folder from modules

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#507]
# Tasks
- [x] **test/authenticate**
- **test/client**
  - [x] community
  - [x] components
  - [x] mobrender
  - [x] utils
  - [x] ux
- **test/client/mobilizations**
  - [x] blocks
  - [x] components
  - [x] templates
  - [x] widgets
- **test/routes**
  - **logged-in**
    - [x] background
    - [x] sidebar
  - [x] **logged-out**

**Comment by gabrielrtakeda** [comment]
@igr-santos, @lpirola, I was wondering to keep the `.spec` files in the same folder as the element they test. I was searching for the conventions adopted by community for a better file structure and I found this article: [A Better File Structure For React/Redux Applications](https://marmelab.com/blog/2015/12/17/react-directory-structure.html) that they mention this:

> I find it harder to spot missing tests for components, or to navigate the file structure once the domain expands. So I try to keep tests in the same directory as the element they test - simply using a -spec.js suffix. If this were Python, tests would even be in the same file! All the scripts related to a bounded context, including tests, are now grouped in a single directory - easy to read and reason about.
