### ISSUE TITLE
Change background color editor when editing custom message after pressure

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#524]

**Comment by gabrielrtakeda** [comment]
Actually, whats's happening is that the **slate-editor** in widget finish custom message form, is rendering with a **different text color** in comparison with when the message renders into mobilization's public view.

| **post-action form**                                                                                                                                                     | mobilization public view                                                                                                                                                 |
|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| <img width="513" alt="screen shot 2017-03-31 at 11 34 32 am" src="https://cloud.githubusercontent.com/assets/5435389/24555084/37bc64c0-1606-11e7-8bdc-af3c6c6ba2a0.png"> | <img width="440" alt="screen shot 2017-03-31 at 11 33 57 am" src="https://cloud.githubusercontent.com/assets/5435389/24555083/37bcade0-1606-11e7-9018-accb5c73dafc.png"> |

I will change the slate-editor background color in post-action form and set the same text color in mobilization public view.

**background color**: `#fff`
**color**: `#666`

**Comment by manuellaos** [comment]
Revisão do Staging: OK
