### ISSUE TITLE
Testar "pages"  que estão sem testes com enzyme

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#53]
## Checklist
- [ ] AutoFireForm
- [ ] DonationWidgetSettings
- [ ] FormWidgetFields
- [ ] FormWidgetForm
- [ ] ListMobilizations
- [ ] Logout
- [ ] MobilizationAnalytics
- [ ] MobilizationBasics
- [ ] MobilizationCity
- [ ] MobilizationCustomDomain
- [ ] MobilizationFonts
- [ ] MobilizationSharing
- [ ] NewMobilization
- [ ] RequireLogin
## W.I.P.
- [x] Empty List (arraste seu item abaixo deste)

**Comment by gabrielrtakeda** [comment]
- [ ] AutoFireForm
- [ ] DonationWidgetSettings
- [ ] FormWidgetFields
- [ ] FormWidgetForm
- [ ] ListMobilizations
- [ ] Logout
- [ ] MobilizationAnalytics
- [ ] MobilizationBasics
- [ ] MobilizationCity
- [ ] MobilizationCustomDomain
- [ ] MobilizationFonts
- [ ] MobilizationSharing
- [ ] NewMobilization
- [ ] RequireLogin

**Comment by lpirola** [comment]
Components will be refactored in #60, probably.
