### ISSUE TITLE
Testar "componentes" que estão sem testes com enzyme

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#54]
## Checklist
- [ ] MobilizationsMenu (aparentemente não está sendo utilizado)
- [ ] FormWidget (Precisa ser refatorado)
- [ ] LoginForm (Precisa ser refatorado, para container)
## W.I.P.
- [x] Empty List (arraste seu item abaixo deste)
- [x] FormWidgetButton
- [x] FormWidgetInput
- [x] FormWidgetMenu
- [x] FormWidgetInputForm
- [x] ColorSchemer
- [x] FontSize
- [x] TellAFriend
- [x] InputCounter
- [x] MobilizationBasicsForm (Refactoring https://github.com/ourcities/hub-client/issues/81)
- [x] ConfigurationsMenu
- [x] CloseButton
- [x] DonationWidgetMenu
- [x] DonationWidget
- [x] TopMenu
- [x] Widget
- [x] TabMenuItem
- [x] MobilizationCard
- [x] MobilizationMenu
- [x] SaveButton
- [x] Label
- [x] WYSIHTMLToolbarColorPicker
- [x] WYSIHTMLToolbarCreateLink
- [x] WYSIHTMLToolbarInsertHTML
- [x] WYSIHTMLToolbarInsertImage

**Comment by gabrielrtakeda** [comment]
## Checklist
- [ ] CloseButton
- [ ] ColorSchemer
- [ ] ConfigurationsMenu
- [ ] DonationWidget
- [ ] DonationWidgetMenu
- [ ] FontSize
- [ ] FormWidget
- [ ] FormWidgetButton
- [ ] FormWidgetInput
- [ ] FormWidgetInputForm
- [ ] FormWidgetMenu
- [ ] InputCounter
- [ ] Label
- [ ] LoginForm
- [ ] MobilizationBasicsForm
- [ ] MobilizationCard
- [ ] MobilizationMenu
- [ ] MobilizationsMenu
- [ ] SaveButton
- [ ] TabMenuItem
- [ ] TellAFriend
- [ ] TopMenu
- [ ] Widget
- [ ] WYSIHTMLToolbarColorPicker
- [ ] WYSIHTMLToolbarCreateLink
- [ ] WYSIHTMLToolbarInsertHTML
- [ ] WYSIHTMLToolbarInsertImage

**Comment by igr-santos** [comment]
Fechado com o PR #94
