### ISSUE TITLE
Better handle with inputs when mobile

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#544]
Try to set better input type to avoid erros from user when filling input.

```

1) A caixa de texto coloca a primeira letra do email em maiúscula e a assinatura não vai.
2) Alguns Androids dão espaço entre o nome e o arroba por exemplo. Aí dá erro e o usuário desiste.

```

**Comment by igr-santos** [comment]
@lpirola where does it happen? Can you explain better?

**Comment by lpirola** [comment]
@igr-santos this occurs when users fill email in form_entries and pressure.

**Comment by gabrielrtakeda** [comment]
@igr-santos, I'll take a look into this issue, ok?
