### ISSUE TITLE
Upgrade how we release version?

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#546]
As I started to try to turn the creation of change log automatic and bump version easy, I found these tool.
https://github.com/conventional-changelog/standard-version

Maybe we could start with a PR to remove current bump script and create a npm script command to release. This will a much better approach I guess.

What do you guys think? @gabrielrtakeda @igr-santos

**Comment by gabrielrtakeda** [comment]
Great @lpirola!

I really think that this approach is a better way to handle the version changes of the project. Mostly using the [Conventional Commits](https://conventionalcommits.org/) besides some another commit message conventions like in [this post](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html) to make the commit messages more readable and more easy to understand, beyond to make the [standard-version](https://github.com/conventional-changelog/standard-version) tool that you have mentioned to work.

I agree with put in practice and change the flow that we are working with commits using the [standard-version](https://github.com/conventional-changelog/standard-version) that seems pretty handy to me.
