### ISSUE TITLE
Warning: ReactTestUtils has been moved to react-dom/test-utils. Update references to remove this warning.

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde#554]
# Description
When run the tests, this warning is dispatching:

```
Warning: ReactTestUtils has been moved to react-dom/test-utils. Update references to remove this warning.
```

I am googled a bit and I found [this comment](https://github.com/airbnb/enzyme/issues/875#issuecomment-293733266) that leads me to the [React v15.5.0 blog post](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes).

Basically, is need to make this:

```patch
-import React, { Component, PropTypes } from 'react'
+import PropTypes from 'prop-types';
+import React, { Component } from 'react';
```

It have the [React-PropTypes-to-prop-types](https://github.com/reactjs/react-codemod#react-proptypes-to-prop-types) codemods but, it seems that does not migrate the PropTypes of stateless components.

To install the codemods, follow the following steps:

1. `npm install -g jscodeshift`
1. `git clone https://github.com/reactjs/react-codemod.git` (inside the root of the project)
1. `cd react-codemod  && npm install`

To run the migration is:
- `jscodeshift -t react-codemod/transforms/React-PropTypes-to-prop-types.js <path>`
As described in [React-PropTypes-to-prop-types](https://github.com/reactjs/react-codemod#react-proptypes-to-prop-types) section

**Comment by lpirola** [comment]
@gabrielrtakeda https://github.com/airbnb/enzyme/issues/875

**Comment by gabrielrtakeda** [comment]
After the React upgrade and codemods execution, the dependency packages warnings like examples below was starts to dispatch.

**React.createClass warning**
```
Warning: FontAwesome: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.
```
I opened an issue in `react-fontawesome` module danawoodman/react-fontawesome#45 to fix this.

**New PropTypes warning**
```
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
```

**Comment by gabrielrtakeda** [comment]
It needs to upgrade the `react-fontawesome` module to >= v1.6.0
Issue opened in nossas/slate-editor#18
