### ISSUE TITLE
Mobilization http://cpidoaborto.meurio.org.br is not working

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde#556]
# Description
It needs to investigate why the mobilization http://cpidoaborto.meurio.org.br is not working and fix it.

**Comment by gabrielrtakeda** [comment]
On the development build using the API with production database dump, the client application show the following error when try to access the described mobilization:

```
Error: Sorry, media type not found.
    at Media.render (/Users/gabrielrtakeda/code/bonde-client/client/components/editor-draft-js/Toolbar/MediaControls/Media.js:43:13)
    at /Users/gabrielrtakeda/code/bonde-client/node_modules/react-dom/lib/ReactCompositeComponent.js:796:21
    at measureLifeCyclePerf (/Users/gabrielrtakeda/code/bonde-client/node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)
```

It seems like a DraftJS issue.
Maybe a minor version of the package was installed?
For now, I will fix this bug to solve the problem to render the mobilization.

**Comment by lpirola** [comment]
@gabrielrtakeda Could be a recent upgrade we did.

**Comment by gabrielrtakeda** [comment]
Yes @lpirola. But I think it is not a big problem.
