### ISSUE TITLE
Testar "reducers" que estão sem testes com enzyme

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#57]
## Checklist
- [x] https://github.com/ourcities/hub-client/pull/75 Auth
- [x] https://github.com/ourcities/hub-client/pull/77 Organizations
- [x] https://github.com/ourcities/hub-client/pull/80 Fix Organizations response superagent

**Comment by gabrielrtakeda** [comment]
## Checklist
- [ ] Auth
- [ ] Organizations
