### ISSUE TITLE
Add from_email to community config

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#587]
This commit add the param custom_from_email to community

https://github.com/nossas/bonde-server/commit/6ff92a5868924970e3e8b3e153289301a5c128c9

**Comment by lpirola** [comment]
We could add this info to this page:

<img width="1440" alt="screen shot 2017-05-15 at 11 46 08" src="https://cloud.githubusercontent.com/assets/14948/26063336/20795e2c-3964-11e7-8b68-2d7910d7ed28.png">

Label to this field could be: "From e-mail to notifications"

The format could be: "Lucas Pirola<lpirola@teste.com>"

**Comment by lpirola** [comment]
Lucas Pirola < lpirola@teste.com >

**Comment by igr-santos** [comment]
@lpirola this field has a value default?

**Comment by lpirola** [comment]
@igr-santos has Bonde<contato@bonde.org>.

Right @forevertonny ?
