### ISSUE TITLE
Make an input filter by suggestions

### ISSUE THREAD

**Issue by igr-santos** [nossas/bonde#593]
Could be:

```
// Suggestions format array [{ suggestionGroup: [ suggestion1, suggestion2 ] }]

SuggestionsFilter.propTypes = {
  onChange: PropTypes.func,
  value: PropTypes.any,
  suggestions: PropTypes.array
}
```

**Comment by igr-santos** [comment]
Estou pensando em usar essa biblioteca [react-select](https://github.com/JedWatson/react-select). Eu também gostei bastante do modelo de documentação da biblioteca no README acredito que podemos começar com nossos módulos por esse modelo.

**Comment by lpirola** [comment]
@igr-santos vai ser lindo ver esse componente por lá, pelo que puder avaliar me pareceu um biblioteca bem aceita pela comunidade, vamo q vamo!
