### ISSUE TITLE
Change architecture to work with modules

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#60]

**Comment by gabrielrtakeda** [comment]
# Introduction

Here will be listed the migration required modules.

## Migration
- [x] FormWidget to `app/modules/Widget/plugins/Form`
- [ ] DonationWidget
- [ ] MatchWidget

## Refactoring
- [ ] FormWidget
- [ ] DonationWidget
- [ ] MatchWidget

## Probably independent modules
- [ ] TellAFriend

**Comment by gabrielrtakeda** [comment]
Needs to fix FormWidget settings "Relatório" tab. Check if imports references is correct.

**Comment by gabrielrtakeda** [comment]
Needs to fix Mobilization activist view. Maybe is some incorrect import references.

#### Error:

```
ROUTER ERROR:   Error: Element type is invalid: expected a string (for built-in components) or   a class/function (for composite components) but got: undefined. Check the ren  der method of `Widget`.
```

**Comment by gabrielrtakeda** [comment]
Renamed branch to [add-modularized-structure](https://github.com/ourcities/hub-client/tree/add-modularized-structure) for better understanding of what it is about and, add automated deploy branch name pattern for deploy to staging.

**Comment by igr-santos** [comment]
My option about that structure:

```
app
├───modules (modules for later)
|   ├───Mobilization (module structure)
|   │   │   index.js
|   │   │   routes.js
|   │   │   reducer.js
|   |   |   actions.js
|   │   │
|   │   ├───containers (root nodes for route, here and only here should connect mapStateToProps)
|   |   |   |   WrapperDashboard.js (responsible for render children with mapped props)
|   |   |
|   │   ├───components
|   │   │   │   ConfigMenu.jsx
|   │   │   │   Card.jsx
|   │   │   │   ...
|   │   │
|   │   └───pages (responsible for mount page connect props with component)
|   │       │   NewBlank.jsx
|   │       │   NewTemplate.jsx
|   │       │   ...
|   |
└───components (reusable components shared by all modules)
    |   └───FormUtils
    |       |   index.js
    |       |   ...
    |
    |   index.js
```

What are you thinking about that?

**Comment by lpirola** [comment]
Turns out that we moved forward with this structure.
