### ISSUE TITLE
Remove the validation www-redirect with blacklist in server-side

### ISSUE THREAD

**Issue by igr-santos** [nossas/bonde#611]
## How to

- Check if blacklisted urls (https://github.com/nossas/bonde-client/blob/feature-put-www-custom-domain/server/redirect.blacklist) are configured on Route53 with prefix `www`
- Update urls of mobilizations with urls same as blacklist of redirect (https://github.com/nossas/bonde-client/blob/feature-put-www-custom-domain/server/redirect.blacklist) to the prefix `www.`
- Change code that implement redirect with blacklist in server-side (https://github.com/nossas/bonde-client/blob/feature-put-www-custom-domain/server/index.js#L100-L111)

**Comment by gabrielrtakeda** [comment]
**Query to update the custom domain of mobilizations that not use the www.**

```sql
UPDATE mobilizations
SET custom_domain = 'www.' || custom_domain
WHERE id IN
    (SELECT id
     FROM mobilizations
     WHERE custom_domain ~* '^(?!www).+');
```

**Comment by gabrielrtakeda** [comment]
Rebase 👇
