### ISSUE TITLE
Filed "day to transfer" at recipient community page must be validated before submit

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#615]
If we choose day 31, what happens?
We must validate if number is greater than 31.
What happens on 31 or 30 of february?

**Comment by igr-santos** [comment]
We solved the problem with february, exchange a open field to field with range of days

**Ranges**
Monthly: [1, 6, 11, 16, 21, 26]
Weekly: [1, 2, 3, 4, 5]
