### ISSUE TITLE
Add warning when configure pagarme details at community options

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#628]
```Atenção: As doações só ficam disponíveis 31 dias após a transação de cartão de crédito ter sido criada (29 dias corridos + 2  dias úteis) no caso de transações com uma parcela e 2 dias úteis após o pagamento do boleto bancário. Caso a transação tenha de 2 a 12 parcelas, o recebimento normal será da seguinte forma: primeira parcela em 31 dias, segunda em 61, terceira em 91, e assim por diante.```

**Comment by gabrielrtakeda** [comment]
@lpirola, is it on community **recipient** settings page?
