### ISSUE TITLE
Improvements when user choose howto publish mobilization

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#629]
- Trocar texto de opções de domínio na mobilização
  - [x] Quero usar um novo sub-domínio
  - [x] Quero usar um domínio principal cadastrado na comunidade
  - [x] Quero direcionar para um domínio externo
- [x] Por padrão vir aberto opção de novo sub domínio de um domínio já cadastrado
- Adicionar link e explicação no topo para criar novos domínios na comunidade mesmo se já tiver um cadastrado
  - [x] explica o q é comunidade e pq cadastrar domínios lá ****************** TEXTO
- [x] Adicionar opção especial para configurar domínio root

**Comment by lpirola** [comment]
Mensagem do topo:

```
Estamos quase lá, agora você precisa escolher o endereço será utilizado. Se você já cadastrou um domínio na comunidade, pode selecionar abaixo qual das opções melhor se encaixa! 

Para fazer o cadastro de um novo domínio, clique aqui.
```

**Comment by gabrielrtakeda** [comment]
@lpirola Did you get the text of the task below?
```
explica o q é comunidade e pq cadastrar domínios lá ****************** TEXTO
```

**Comment by lpirola** [comment]
@gabrielrtakeda I guess this text is fine, maybe something like:

"
Estamos quase lá, antes de publicar sua mobilização é preciso escolher a url que será usada para publicação.

Já cadastrou um domínio na comunidade? Selecione abaixo qual das opções melhor se encaixa. 
Quer cadastrar um novo domínio? Clique aqui.
"

**Comment by gabrielrtakeda** [comment]
Nice, @lpirola! I will update it with this text.

**Comment by gabrielrtakeda** [comment]
rebase 👇

**Comment by gabrielrtakeda** [comment]
rebase 👇

**Comment by gabrielrtakeda** [comment]
Merged into master in **Release v0.5.6 #652**
