### ISSUE TITLE
Add option to use bonde.org domain as default domain

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#631]
- [x] Adicionar edição do campo de slug na aba de infos básicas
- [x] Adicionar rendericação do erro quando já existir slug cadastrada
- [x] Notificar usuário que utilizar domínio externo, quando o slug for alterado

**Comment by gabrielrtakeda** [comment]
rebase 👇

**Comment by gabrielrtakeda** [comment]
Merged into master in **Release v0.5.6 #652**
