### ISSUE TITLE
Improve how we set new domain at community page close #613

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#632]
- [x] Carregar o DNS para o domínio selecionado, quando estiver visualizando sub-domínios (voltar da api os nameserver de dns)
- [x] Adicionar CLIQUE no domínio para carregar sub domínios e Servidores DNS
- [x] Ao remover, aviso(modal) está aparecendo abaixo do botão "Adicionar novo subdomino externo" 
- [x] Ao remover, aviso(modal) continua aberto se clico em outro elemento da página
- [x] Adicionar mensagem de feedback após verificar se alteração foi feita no servidor DNS ****************** TEXTO

**Comment by igr-santos** [comment]
@lpirola qual a mensagem de feedback?

**Comment by lpirola** [comment]
@igr-santos 

Success: "Uhuu! Os servidores DNS foram sincronizados, agora você pode configurar seu e-mail e outros serviços, assim como escolher o domínio da sua mobilização."

Fail: "Ooops! A sincronização ainda está pendente, você pode tentar de novo em alguns minutos."

**Comment by gabrielrtakeda** [comment]
rebase 👇

**Comment by igr-santos** [comment]
Closes https://github.com/nossas/bonde-client/issues/613

**Comment by gabrielrtakeda** [comment]
Merged into master in **Release v0.5.6 #652**
