### ISSUE TITLE
Bad user expierence whn community have a lot of domains

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#638]

**Comment by igr-santos** [comment]
@lpirola how to improve this page? i don't have any idea

**Comment by lpirola** [comment]
@igr-santos this issue is related to show subdomain list, when you have more than ten domains, the scroll is too long. A solution suggested to change to table or change height from each row.

I will change owner of this issue to @gabrielrtakeda maybe he can look and found a better solution.

**Comment by gabrielrtakeda** [comment]
rebase 👇
