### ISSUE TITLE
Modal editor show to public version when a link is empty

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#654]

**Comment by gabrielrtakeda** [comment]
# Solution
To solve this, follow the steps described in [Purge empty links v2.6
](https://github.com/nossas/slate-editor/wiki/Purge-empty-links-v2.6) from [nossas/slate-editor](https://github.com/nossas/slate-editor) repository.

# SQL to get the data
It needs to run the sql query below, to get the widgets that uses the slatejs editor to run the migration script.

```sql
SELECT id,
       (settings -> 'content')::json AS doc
FROM widgets
WHERE settings -> 'content' ~ '^{"document';
```

**Comment by gabrielrtakeda** [comment]
Rebase 👇
