### ISSUE TITLE
Add support to multiple targets at pressure widget

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#657]
- [x] Change helper text to add warning about how add targets
- [x] Improve height to field "corpo do e-mail"
- [x] Improve exibithion format when adding targets ( avoid scroll the page, maybe adding a container to scroll targets)
- [x] Add text helper saying how targets will be ordered 
- [x] Add counter total number of targets
- [x] Add counter total number of targets to public view
- [x] Order by random targets at public view
- [x] Add button to remove all targets
- [x] Add a textarea to insert multiple targets at once

**Comment by gabrielrtakeda** [comment]
@lpirola I just do not understand how the ordering will work.. Basically, the order of targets is depending of the order that user inputs them..

**Comment by gabrielrtakeda** [comment]
May it should have a `<select>` with some options like **ascending** or **descending** by target name?

**Comment by lpirola** [comment]
@gabrielrtakeda At task I mean "text helper" not some ui helper, sorry.

**Comment by gabrielrtakeda** [comment]
Ok, I was just misunderstanding..

**Comment by gabrielrtakeda** [comment]
So, we do not need to handle the order of the targets, right?

**Comment by lpirola** [comment]
@gabrielrtakeda nope. In public view, I like to randomize to always show everybody as much as we can.

**Comment by gabrielrtakeda** [comment]
Nice! Now I get the reason of random order of targets. Thanks @lpirola 😉

**Comment by gabrielrtakeda** [comment]
About the validation, if something was wrong on pattern of target list, as you have mentioned on the meeting, I will show a generic error saying that something is wrong on it, ok?

**Comment by lpirola** [comment]
@gabrielrtakeda Ok! Be careful to avoid cache conflicts, try to randomize with some run time way.

**Comment by gabrielrtakeda** [comment]
Great @lpirola! Thanks for remind me, I almost forgot about it heh 😅

**Comment by gabrielrtakeda** [comment]
Rebase 👇
