### ISSUE TITLE
Continue button doesn't redirect to the second step

### ISSUE THREAD

**Issue by manuellaos** [nossas/bonde#662]
![image](https://user-images.githubusercontent.com/25207509/27049440-b659d78c-4f85-11e7-94b0-3f74d6384994.png)

When I click on 'continue' it does not redirect me to the second step.

**Comment by gabrielrtakeda** [comment]
@manuellaos which branch that are you using? May it needs to pull some changes from develop..

**Comment by gabrielrtakeda** [comment]
Sorry, I was thinking that was on dev heh, I will resolve this bug and, it will be merged into master together with the next release in **v0.5.8**
