### ISSUE TITLE
Handle non-authenticated request on api GraphQL or REST 

### ISSUE THREAD

**Issue by igr-santos** [nossas/bonde#672]

**Comment by lpirola** [comment]
@igr-santos before we do #678 we must address a small fix to list mobilizations and community because it is occurring more often than we think the error with invalid token

**Comment by lpirola** [comment]
@igr-santos Did you have any idea at how do you handle token validation ata action layer?

We could be using some over engineering doing something like that?

**Comment by igr-santos** [comment]
@lpirola `redux-auth-wrapper` validate on render layer and when I have a problem with invalid token like this case I need of validation on requesting layer like this commit (cf5b981b429565fb3b461a146b78ffe62321721c)

**Comment by lpirola** [comment]
blocked because #705
