### ISSUE TITLE
Add scoped permissions to users

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#678]
- [ ] Evaluate use of https://github.com/mjrussell/redux-auth-wrapper
- [ ] Setup admin and common user rules

**Comment by igr-santos** [comment]
@lpirola this librarie resolve the problem of roles and validation current user, but when the client request on API Rest or GraphQL (async request) with user invalid, because of cache on server-side they not resolve

**Comment by igr-santos** [comment]
@lpirola this librarie resolve the problem of roles and validation current user, but when the client request on API REST or GraphQL (async request) with user invalid, because of cache on server-side and I need a validation on actions layer and redux-auth-wrapper is validation for store layer.

**Comment by lpirola** [comment]
@igr-santos we haven't cache at server side. Could you explain better what did you mean?

If I understand right, we must handle token invalidation at actions layer. 

Maybe we must delay the adoption of this library.
