### ISSUE TITLE
Update slate editor to use pt-br labels

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#688]

**Comment by gabrielrtakeda** [comment]
@lpirola I will migrate this issue to [nossas/slate-editor](https://github.com/nossas/slate-editor) repo, ok?

**Comment by lpirola** [comment]
@gabrielrtakeda this issue is related to change you will need to do at this repo. I create an issue to change default labels at editor repo.

**Comment by gabrielrtakeda** [comment]
Ok, nice!

**Comment by gabrielrtakeda** [comment]
Rebase 👇
