### ISSUE TITLE
Image background can't not be removed from block

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#703]

**Comment by lpirola** [comment]
related #474

**Comment by gabrielrtakeda** [comment]
@igr-santos, it would be great if it has PR to merge these changes back to the branch develop..

**Comment by igr-santos** [comment]
@gabrielrtakeda I not finished, I do this issue together #704

**Comment by gabrielrtakeda** [comment]
Ok. I will mark this PR with the **dont-merge** label. @igr-santos when you get finish this, can you remove this label so that we know we can merge it back to the branch develop?

**Comment by gabrielrtakeda** [comment]
Rebase 👇
