### ISSUE TITLE
Upgrade react-router to v4.1.1

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#705]
# Related pull-requests
- Update dependencies to enable Greenkeeper 🌴 #709

# Description
It needs to upgrade the **react-router** package to `v4.1.1 `, that was indicated by greenkeeper bot. Make the necessary changes on the project to not break the project with this upgrade.

**Comment by igr-santos** [comment]
**Branch:** https://github.com/nossas/bonde-client/tree/feature-react-router-v3

**Comment by igr-santos** [comment]
Change following files to use `react-router-redux` redirect:

- [ ] `./client/account/redux/action-creators/async-retrieve-password.js:21: browserHistory.push(paths.login())`
- [ ] `./client/account/redux/action-creators/logout.js:8: browserHistory.push('/login')`
- [ ] `./client/mobrender/components/mobilization.js:34: browserHistory.push(paths.mobilizationTemplatesChoose(mobilization))`
- [ ] `./client/mobrender/components/widget.js:34: browserHistory.push(redirect)`
- [ ] `./client/mobilizations/widgets/__plugins__/donation/components/__donation__/index.js:46: browserHistory.push(paths.donation(mobilization.id, widget.id))`
- [ ] `./client/mobilizations/widgets/__plugins__/pressure/components/__pressure__.js:65: browserHistory.push(`
- [ ] `./client/mobilizations/widgets/__plugins__/form/components/__form__.js:40: browserHistory.push(paths.fieldsMobilizationWidget(mobilization.id, widget.id))`
- [ ] `./routes/admin/not-authenticated/account-login/page.connected.js:51: browserHistory.push('/')`
- [ ] `./routes/admin/not-authenticated/account-register/page.js:20: browserHistory.push(Paths.login())`
- [ ] `./routes/admin/authenticated/sidebar/mobilizations-launch/page.js:78: browserHistory.push(`
- [ ] `./routes/admin/authenticated/sidebar/community-settings/domain-create/page.js:102: onClick={() => browserHistory.push(paths.communityDomain())}`
- [ ] `./routes/admin/authenticated/sidebar/community-settings/domain-create/page.js:168: onClick={() => browserHistory.push(paths.communityDomain())}`
- [ ] `./routes/admin/authenticated/sidebar/community-settings/domain-create/page.js:180: browserHistory.push(query.next)`
- [ ] `./routes/admin/authenticated/sidebar/community-settings/domain-create/page.js:222: onClick={() => browserHistory.push(paths.communityDomain())}`
- [ ] `./routes/admin/authenticated/sidebar/community-settings/domain/page.js:189: onClick={() => browserHistory.push(Paths.communityDomainCreate())}`
- [ ] `./routes/admin/authenticated/sidebar/mobilizations-edit/page.js:18: browserHistory.push(paths.createBlock(mobilization))`
- [ ] `./routes/admin/authenticated/sidebar/mobilizations-launch-end/page.js:31: <Button onClick={() => browserHistory.push(paths.editMobilization(id))}>`
- [ ] `./routes/admin/authenticated/sidebar/blocks-create/page.js:141: browserHistory.push(`
- [ ] `./routes/admin/authenticated/sidebar/templates-choose-global/page.js:19: handleGoBack={() => browserHistory.push(paths.mobilizationTemplatesChoose(mobilization))}`
- [ ] `./routes/admin/authenticated/sidebar/templates-choose-global/page.js:23: browserHistory.push(paths.editMobilization(mobilization.id))`
- [ ] `./routes/admin/authenticated/sidebar/mobilizations-new/page.js:16: mobilization && browserHistory.push(`
- [ ] `./routes/admin/authenticated/sidebar/templates-choose-custom/page.js:23: browserHistory.push(paths.editMobilization(mobilization.id))`
- [ ] `./routes/admin/authenticated/sidebar/mobilizations-settings-domain/page.js:19: redirectToCreateDNS={() => browserHistory.push(paths.communityDomainCreate())}`
- [ ] `./routes/admin/authenticated/sidebar/mobilizations-list/page.js:35: browserHistory.push(paths.editMobilization(mobilization.id))`
- [ ] `./routes/admin/authenticated/sidebar/templates-create/page.js:42: browserHistory.push(paths.mobilizations())`
-`./routes/admin/authenticated/logout/page.js:10: this.props.logout().then(() => browserHistory.push(Paths.login()))`
-`./routes/admin/authenticated/external/community-list/page.js:12: browserHistory.push(paths.communityAdd())`
- [ ] `./routes/admin/authenticated/external/community-list/page.js:18: browserHistory.push(paths.mobilizations())`
- [ ] `./routes/admin/authenticated/external/community-new/page.js:20: browserHistory.push(paths.communityList())`
