### ISSUE TITLE
Button to "unpublish" a mobilization's domain

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde#712]
# Description
It needs to add a button to turn down a mobilization from public access.
May add a button into the mobilization's **domain** settings page would be a good idea.

<img width="924" alt="screen shot 2017-06-26 at 20 19 01" src="https://user-images.githubusercontent.com/5435389/27564467-349dfe10-5aae-11e7-84d7-541dda7cc8e7.png">

**Comment by lpirola** [comment]
@gabrielrtakeda how these button will work behind the scenes?

**Comment by gabrielrtakeda** [comment]
@lpirola just letting the `custom_domain` field empty on the database.

**Comment by lpirola** [comment]
@gabrielrtakeda maybe we will need to disable something at cache too but I agree if you want to follow with this issue and implement this unpublish button.

**Comment by gabrielrtakeda** [comment]
Damm, I forgot the cache lol
Yeah, may it needs to handle this on the cache too but anyway I think we need a button like this to make the mobilization's domain empty. I do not know for sure if, we submit the mobilization's domain form letting the domain field empty, it will be saved on the database..

Anyway, the case on the cache that you have mentioned @lpirola, is a fact and needs to be handled too.
