### ISSUE TITLE
JWT token generation return 403 forbidden from graphql

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#730]

**Comment by igr-santos** [comment]
Esse erro ocorre quando o JWT Token salvo em cache é inválido, quando é feito a requisição (GraphQL) um middleware aplicado em `client/store.js` no `ApolloClient` checa se existe JWT Token em cache e autentica a requisição.

No momento em que estou fazendo a requisição tenho acesso ao nome da `query/mutation` executada, e com isso consigo validar se aquela requisição precisa ou não ser autenticada, a partir desse momento eu deixo de ter problemas na função de autenticação (GraphQL) e toda vez que o usuário autenticar eu tenho um novo JWT Token gerado.

**Comment by lpirola** [comment]
@igr-santos não entendi muito bem o comentário, isso quer dizer que o problema está resolvido ou que essa é a solução que você vai implementar? Se for o segundo ficou confuso, o que exatamente você vai tentar fazer.

**Comment by igr-santos** [comment]
@lpirola isso é a solução que eu vou implementar, mas pode ser que não resolva 100% do problema, pra resolver 100% do problema temos que redirecionar o usuário para o login sempre que houver um error 403 na requisição GraphQL
