### ISSUE TITLE
Update metrics to support new donations index

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#742]
https://github.com/nossas/bonde-server/issues/297

Some donations metrics was missing from first dashboard version, now we could update to support all planned metrics.

**Comment by igr-santos** [comment]
@lpirola e @gabrielrtakeda queria tirar uma dúvida sobre o funcionamento de metricas. Hoje nós trabalhamos em cima de várias funções dentro da base de dados, porém executando uma única query no GraphQL, dessa forma eu possuo uma transação única, tornando as funções interdependentes. Tentando fragmentar a query, percebi que esse comportamento seria descontinuado, e quero entender se a criação de uma única query tem haver com alguma necessidade imposta anteriormente.

**Comment by lpirola** [comment]
@igr-santos esse é um exemplo de mobilização que tem problema com as pressões criadas e o total retornado pela api. /mobilizations/158/widgets/2425/pressure/finish
