### ISSUE TITLE
Add option to set default color to form_entries widget

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#747]

**Comment by lpirola** [comment]
@igr-santos @gabrielrtakeda O que acham que vale mais a pena fazer para começar a salvar e aplicar uma cor para a widget de form_entries?

**Comment by gabrielrtakeda** [comment]
@lpirola, acho que adicionar um colorpicker nas configurações básicas, igual tem para as widgets de pressure e donation seria o mais fácil... mas, se for parar pra pensar um pouco mais na usabilidade, talvez ter um colorpicker para as widget na própria página de edição da mobilização seria bem interessante...
