### ISSUE TITLE
Create a style guide document

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde#759]
# Description
O intuito dessa issue é criar um documento para identificar os padrões de componentes, mapear quais componentes são utilizados atualmente e que queremos manter ou, quais não queremos manter. Abaixo segue lista de perguntas que deverão ser respondidas com esse documento:

* Listar componentes que são utilizados de forma padronizada e gostaria de mantê-lo
* Listar componentes que são utilizados de forma padronizada e não gostaria de mantê-lo
* Listar componenets que não são utilizados de forma padronizada
* Listar páginas e marcar se utilizão os componentes padronizados ou não

**Comment by gabrielrtakeda** [comment]
## Routes

- [x] (admin) /
- [x] (admin) /account/edit
- [x] (admin) /account/retrieve
- [x] (admin) /community
- [x] (admin) /community/domain
- [x] (admin) /community/domain/add
- [x] (admin) /community/info
- [x] (admin) /community/invite
- [x] (admin) /community/mailchimp
- [x] (admin) /community/new
- [x] (admin) /community/recipient
- [x] (admin) /community/report
- [x] (admin) /login
- [x] (admin) /mobilizations
- [x] (admin) /mobilizations/:mobilization_id/analytics
- [x] (admin) /mobilizations/:mobilization_id/basics
- [x] (admin) /mobilizations/:mobilization_id/blocks/create
- [x] (admin) /mobilizations/:mobilization_id/customDomain
- [ ] (admin) /mobilizations/:mobilization_id/edit
- [x] (admin) /mobilizations/:mobilization_id/launch
- ~(admin) /mobilizations/:mobilization_id/launch/end~
- [x] (admin) /mobilizations/:mobilization_id/metrics
- [x] (admin) /mobilizations/:mobilization_id/sharing
- [x] (admin) /mobilizations/:mobilization_id/templates/choose
- [x] (admin) /mobilizations/:mobilization_id/templates/choose/custom
- ~(admin) /mobilizations/:mobilization_id/templates/choose/global~
- [x] (admin) /mobilizations/:mobilization_id/templates/create
- [x] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/donation
- [x] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/donation/autofire
- ~(admin) /mobilizations/:mobilization_id/widgets/:widget_id/donation/export~
- [x] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/donation/finish
- [x] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/form
- [x] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/form/autofire
- [x] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/form/export
- [x] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/form/fields
- [x] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/form/finish
- [x] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/pressure
- [x] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/pressure/autofire
- [x] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/pressure/email
- [x] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/pressure/finish
- [x] (admin) /mobilizations/new
- [x] (admin) /mobilizations/templates/list
- [x] (admin) /register
- [ ] (public) /subscriptions/:id/edit

**Comment by gabrielrtakeda** [comment]
### Mapeamento de estilos dos botões
Lista de estilos de botões e seus respectivos caminhos de componente e/ou utilização/implementação.

1. `client/ux/components/button/index.js`
1. `client/components/editor-draft-js/Toolbar/ColorControls/ColorPickerButton.js`
1. `client/mobilizations/widgets/__plugins__/content/components/action-button.js`
1. `client/mobilizations/widgets/__plugins__/form/components/button.js`
1. `client/components/forms/control-buttons.js`
1. `client/mobilizations/widgets/__plugins__/form/components/input-form.js`
1. `client/ux/components/flat-form/index.js`
1. `client/components/forms/button.js`
1. `client/mobilizations/templates/components/template-selectable-list.js`
1. `client/community/components/force-download-via-ajax.js`
1. `client/mobilizations/widgets/components/input-tag.js`
1. `client/mobilizations/widgets/__plugins__/donation/components/__donation__/index.js`
1. `client/mobilizations/widgets/__plugins__/pressure/components/pressure-form/index.js`
1. `client/components/share/facebook-share-button.js`
1. `client/components/share/twitter-share-button.js`
1. `client/components/share/whatsapp-share-button.js`
1. `client/mobrender/widgets/draft/components/draft-button.js`
1. `client/components/navigation/navbar/navbar-button.js`

![buttons](https://user-images.githubusercontent.com/5435389/28326339-e0908a80-6bb6-11e7-8a13-2ab6b172de84.jpg)

**Comment by gabrielrtakeda** [comment]
### Mapeamento de estilos dos formulários

![forms](https://user-images.githubusercontent.com/5435389/28330078-97e2bb1c-6bc2-11e7-93af-6e65d108a7f1.jpg)

**Comment by gabrielrtakeda** [comment]
### Mapeamento de tipos de layout (estrutura de página)

![layouts](https://user-images.githubusercontent.com/5435389/28331361-1cbdbc0c-6bc7-11e7-81e7-a36136f92429.jpg)

**Comment by lpirola** [comment]
Estilo de documentação padrão que pode servir de inspiração. https://github.com/sruda/steroidesign/blob/master/Airbnb.md

**Comment by lpirola** [comment]
Base de elementos css que podemos usar como referência.

https://github.com/claviska/shoelace-css - without sass

https://github.com/jgthms/bulma
