### ISSUE TITLE
TypeError: Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#783]
https://sentry.io/nossas-cidades/bonde-website/issues/321117497/

```
TypeError: Cannot read property 'slice' of undefined
  at C (/bonde-assets/main.bundle.js:1:706188)
  at d._constructComponentWithoutOwner (/bonde-assets/vendor.bundle.js:1:756424)
  at d._constructComponent (/bonde-assets/vendor.bundle.js:1:756278)
  at d.mountComponent (/bonde-assets/vendor.bundle.js:1:755460)
  at Object.mountComponent (/bonde-assets/vendor.bundle.js:1:809946)
...
(45 additional frame(s) were not displayed)
```

**Comment by lpirola** [comment]
@gabrielrtakeda Esse erro tem a ver com a edição de subscription de um determinado usuário, já que para outros ele funciona de boua.

**Comment by gabrielrtakeda** [comment]
@lpirola o erro tá acontecendo em algum trecho desse código:

**client/subscriptions/forms/credit-card-form.js**
```jsx
<div className='mb3 lightgray'>
  <b className='block mb1'>Dados do último cartão</b>
  <div>
    <span className='caps'>{card.brand}: </span>
    {card.firstDigits.slice(0, 4)} {card.firstDigits.slice(4, 6)}XX XXXX {card.lastDigits}
  </div>
  <div>Nome: <span className='caps'>{card.holderName}</span></div>
  <div>
    Validade: {card.expirationDate.slice(0, 2)}/{card.expirationDate.slice(2, 4)}
  </div>
</div>
```

Quando o formulário de edição dos dados de cartão de crédito tenta usar informações do último cartão utilizado pelo ativista...

**Comment by gabrielrtakeda** [comment]
Como workaround desse bug, colocar uma verificação se o objeto `card` tá vazio já resolve mas, talvez seja importante saber o por quê que o objeto `card` tá vazio...

**Comment by lpirola** [comment]
@gabrielrtakeda segura essa correção vamos ver se tem algo no bd.

@devton consegue dar uma olha porque no banco esse dado está retornando vázio? Acho que consegue os dados no sentry.

**Comment by gabrielrtakeda** [comment]
@lpirola mas talvez também nem seja algo no db.. pode ser que alguma coisa (quando digo alguma coisa, me refiro a algum `connect` do componente e tals...) no client esteja fazendo com que esse objeto fique `undefined` e tals.. de qualquer forma vou dar um check nisso também...

**Comment by gabrielrtakeda** [comment]
Rebase 👇
