### ISSUE TITLE
Add warning when domain could not be added by any reason

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#788]

**Comment by igr-santos** [comment]
@lpirola a API não devolve uma mensasgem customizada para quando é inserido um domínio já existente na base, ela retorna um erro generico `500 Internal Server Error`, segue o log da API:

```
api_1       | I, [2017-08-07T10:42:16.800761 #8]  INFO -- : Completed 500 Internal Server Error in 52ms (ActiveRecord: 1.5ms)
api_1       | D, [2017-08-07T10:42:16.801019 #8] DEBUG -- : PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_dns_hosted_zones_on_domain_name"
api_1       | DETAIL:  Key (domain_name)=(minhabeaga.org) already exists.
api_1       | : INSERT INTO "dns_hosted_zones" ("domain_name", "community_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id" excluded from capture: DSN not set
api_1       | F, [2017-08-07T10:42:16.802203 #8] FATAL -- : 
api_1       | ActiveRecord::RecordNotUnique (PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_dns_hosted_zones_on_domain_name"
api_1       | DETAIL:  Key (domain_name)=(minhabeaga.org) already exists.
api_1       | : INSERT INTO "dns_hosted_zones" ("domain_name", "community_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"):
api_1       |   app/controllers/dns_hosted_zones_controller.rb:32:in `create'
```

Eu posso tratar de forma generica, ou alterar a API pra responder de forma amigável esse erro.

**Comment by igr-santos** [comment]
Vai ser necessário tratar o erro de forma generica, pois quando tenho um retorno `500 Internal Server Error` o response vem como undefined, impossibilitando tratar a exceção. A forma certa de resolver é fazendo com que a API retorne um response 200/400 com os campos que possuem erro e seus respectivos erros.

**Comment by lpirola** [comment]
@igr-santos melhor genérico do que nada. Nesse caso o problema está na API e como ela deve morrer não queria mais implementar novas coisas.
