### ISSUE TITLE
[Refactor] Make mobilization render a public module

### ISSUE THREAD

**Issue by igr-santos** [nossas/bonde#801]
O objetivo principal é tornar a renderização da mobilização um módulo público, capaz de renderizar qualquer configuração de contexto recebido cujo formato da estrutura seja blocos / widgets.

Objetivo principal (<DonationWidget />): Tornar DonationWidget independente e customizavel para entrada de Contexto / Ação externa ao módulo.

- [x] Documentar API pública (Propriedades)
- [x] Criar teste para `<DonationWidget />` existente
- [x] Refatorar `<DonationWidget />`

**Comment by igr-santos** [comment]
@lpirola e @gabrielrtakeda estou em um ponto chave neste momento em que preciso definir a estrutura de interação dos widgets no momento do render, hoje nós fazemos um arquivo de configuração JS para conseguir listar e renderizar os widgets de acordo com o tipo (kind), vocês imaginam alguma forma de fazer esse tipo de configuração, sem necessariamente criar este arquivo JS?

Como é feito hoje: https://github.com/nossas/bonde-client/blob/develop/client/mobrender/widgets/config.js

Uma das formas que pensei seria criar um HOC público no pacote de renderização, que irá configurar o seu render para gerar o componente que hoje chamamos de `<Mobilization />` essa função seria responsável por receber tais configurações e repassar pros seus componentes privados, desta forma eu tenho um ponto de entrada na API (uma função) em que consigo preparar o módulo para renderização do contexto.

**Comment by lpirola** [comment]
@igr-santos será que nesse caso não é melhor mantermos como está e só alterar o essencial para termos o public module separado, mesmo que seja com esse arquivo de config por hora?

**Comment by igr-santos** [comment]
@lpirola esse é um dos pontos que torna o módulo acoplado, cria uma dependencia interna do arquivo de configuração dentro dos componentes widget e draft.

**Comment by igr-santos** [comment]
Pra que a gente consiga avançar e entender melhor a necessidade, eu vou começar a separar as widgets (Doação será a primeira), meu planejamento é transformar cada widget em um módulo que dispõe do componente público e uma documentação minima das propriedades que esta widget deve receber para renderizar dentro do contexto.

**Comment by lpirola** [comment]
@igr-santos como conversamos, a estratégia adotada é ótima mas continuo sem entender se precisamos mesmo alterar esse arquivo de config do mobrender. Além de um maior isolamento tem algum outro ganho nessa mudança? 

O motivo para não alterar agora, é que gostaria de fazer a revisão sobre a estratégia de uso do json config no mobrender com um olhar mais amplo. Pensar na possibilidade de referenciar pacotes do npm diretamente ou pacotes externos, por exemplo.

Faz sentido?

**Comment by igr-santos** [comment]
@lpirola realmente o que você diz faz sentido, eu vou manter nossa forma de configuração e dar sequência nos testes e refactor de widgets, que nesse momento é o mais importante pra gente

**Comment by igr-santos** [comment]
Encontrei um problema com a renderização de sucesso no momento em que é finalizado a requisição para o metódo de criar a transação, estou analisando o problema para entender o que acontece.

**Comment by lpirola** [comment]
Existem dois pontos que merecem atenção ainda nessa etapa:

* Correção do problema de envio de sucesso para o usuário no retorno de todas as requisições
* Importar o módulo do pagarme pelo webpack

**Comment by gabrielrtakeda** [comment]
Rebase 👇
