### ISSUE TITLE
Unificação dos editores

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#807]
### Estratégia de unificação dos editores:

1. Mapear mobilização e  comunidades que utilizam o editor wysihtml para aviso prévio de mobilizações serão afetadas pela atualização. 
2. Remoção e migração do conteúdo do draftjs sem necessidade de avaliação do mobilizador.
3. Manter a visualização pública do editor do jeito que está em html mas na edição forçar a atualização e não mais dar suporte aos editores antigos. Data de migração forçada: 01/01/2018
3.1 Será apresentado para o usuário um overlay vermelho com a mensagem "Funcionalidade descontinuada", remova a widget e comece novamente.

### Mapa dos afetados

```sql
select 
    -- w.settings::json->>'content' as "content",
    -- c.id as "community_id",
    -- m.id as "mobilization_id",
    -- m.name,
    -- m.updated_at,
    -- c.name,
    m.slug
from widgets w left join blocks b on w.block_id = b.id left join mobilizations m on b.mobilization_id = m.id left join communities c on m.community_id = c.id
where w.kind = 'content' 
and w.settings::json->>'content' ~*'^<' 
-- group by m.name, m.updated_at, c.name, m.slug, c.id, m.id
group by m.slug, m.updated_at
order by m.updated_at desc
```

### Migração do Draftjs

```sql
select 
    -- w.settings::json->>'content' as "content",
    -- c.id as "community_id",
    -- m.id as "mobilization_id",
    -- m.name,
    -- m.updated_at,
    -- c.name,
    m.slug
from widgets w left join blocks b on w.block_id = b.id left join mobilizations m on b.mobilization_id = m.id left join communities c on m.community_id = c.id
where w.kind = 'content' 
and w.settings::json->>'content' ~*'{"entityMap' 
-- group by m.name, m.updated_at, c.name, m.slug, c.id, m.id
group by m.slug, m.updated_at
order by m.updated_at desc
```

* tirar prints antes da migração -- script node que tira prints a partir de urls
* script de migracao "draftjs -> slate-editor" -- script node que transorma objeto draftjs para html e de html para objeto slate-editor e salva no bd
* ferramenta de comparação facilitada -- 
* revisão com a Manu nas mobs impactadas

**Comment by igr-santos** [comment]
https://github.com/nossas/bonde-clients/pull/1029
