### ISSUE TITLE
Refactoring Componentes que utilizam Redux Form.

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde#81]
## Introduction

É necessário que sejam refatorados os componentes que utilizam o redux-form, devido a alta complexidade de efetuar testes de unidade dos mesmos.
## Branch

Um exemplo de componente a ser refatorado é o `MobilizationBasicsForm`.

Inicialmente, criei uma branch para efetuar o refactoring destes componentes contendo já, alguns testes que não necessariamente possuem impedimentos devido a dependência do redux-form.
Nome da branch: `refactor-components-redux-form`

Porém, seria interessante criar uma branch específica pra cada componente a ser refatorado.
## Refactoring

Deverá ser feito uma análise de quais componentes possuem alta taxa de repetição de código, criando componentes genéricos para melhor reaproveitamento.
### Todo:
- [x] MobilizationBasicsForm
### W.I.P.
- [x] Empty List (arraste seu item abaixo deste)

**Comment by igr-santos** [comment]
#86

**Comment by igr-santos** [comment]
Aconteceu o mesmo problema no PR #86 em relação a importação, estou corrigindo no PR #89 para termos um ambiente limpo e rodando
