### ISSUE TITLE
Finish an activists module usable

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#815]

**Comment by igr-santos** [comment]
Avaliando com o @devton chegamos a conclusão que o jeito mais simples no momento é fazer uma nova requisição graphql solicitando apenas o id dos ativistas (sem paginação) para uma lista virtual, onde podemos interar sobre essa informação no cliente, e ao final cada ação recebe como parâmetro a lista com os identificadores de ativistas.

**Comment by lpirola** [comment]
Massa, isso funciona de forma bem genérica me parece. É implementável @igr-santos ?

**Comment by igr-santos** [comment]
Conseguir validar a idéia sobre fazer uma requisição GraphQL após a montagem do componente usando o react apollo client e funcionou como eu esperava.

O próximo passo vai ser refatorar o que foi escrito até o momento. Por quê? Tem algumas composições que precisam de informações de outras composições, vamos chamá-las de composição com depência, um exemplo:

- `Filterable`: disponibiliza propriedades que possibilitam realizar o filtro, na sua estrutura mais simples essas propriedades são, `query`, `onQueryChange`, `onQuerySubmit`.

- `Listable`: disponibiliza propriedades que possibilitam montar uma lista paginada, na sua estrutura mais simples essas propriedades são, `data`, `onNextPage`, `onPreviousPage`

- `Selectable`: disponibiliza propriedades que possibilitam controlar a selação de uma lista, na sua estrutura mais simples essas propriedades são, `selected`, `onSelectAll`, `onSelectRow`

Tanto `Selectable` e `Listable` são composições com depência de `Filterable` que fornece o filtro necessário para realizar suas queries no *GraphQL*.

Com essa estrutura montada, eu consigo aplicar o comportamento de Listar, Selecionar e Filtrar, em qualquer componente, da sequinte maneira:

```
import { FilterableHOC, SelectableHOC, ListableHOC } from './datagrid'
// Componente responsável por renderizar as propriedades
import MyDatagridRender from './my-datagrid-render'

// Opções como query e mapeamento de parâmetro.
const Filterable = FilterableHOC(options)
const Selectable = SelectableHOC(options)

export default Filterable(Selectable(Listable(MyDatagridRender)))
```

@lpirola e @gabrielrtakeda algo a acrescentar?

**Comment by lpirola** [comment]
#591
