### ISSUE TITLE
Wired behaviors after duplicate widget

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#821]
- Quando duplico um bloco com formulário de pressão, dá um bug no qual o formulário fica zerado na tela de edição (na tela pública não). Isso é periogoso pois fico sem saber quais dos dois formulários é o original, e qual é o duplicado. 
- Por algum motivo essa duplicação gera um desordenamento completo de todos os blocos. Alguns blocos sobem, outros descem, mudando a estrutura completa da página.

**Comment by igr-santos** [comment]
@lpirola acabei de entender o erro, ele está na funcionalidade duplicar bloco, essa parte da funcionalidade é complexo devido a nossa estrutura, preciso de tempo para resolver esse problema.

**Comment by lpirola** [comment]
@igr-santos melhor focar nos objetivos da semana e priorizamos isso em outro momento.

**Comment by lpirola** [comment]
Temos outro problema relacionado a isso que é quando o usuário começa uma mobilização a partir de um template e tento move um bloco para o topo
