### ISSUE TITLE
Bug when adding subdomain with extra dot

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#853]

**Comment by rolivegab** [comment]
Consegui configurar todo o ecosistema para funcionar juntamente com o bonde-server em minha máquina. Criei uma comunidade, um domínio, configurei a mudança de servidor DNS no site do registro.br e tentarei agora reproduzir o problema para poder trabalhar em cima dele.

**Comment by rolivegab** [comment]
Após alguns testes identifiquei que a concatenação entre subdomínio e domínio estava sendo feita de forma errada na hora do envio da requisição à api-v1.

Dessa forma, fiz uma pequena correção e agora já é possível adicionar os registros de DNS com subdomínio vazio.

**Comment by rolivegab** [comment]
Durante o processo descobri um novo bug.
Quando você tenta adicionar uma regra de DNS sem especificar o tipo, ele não usa o "A" como padrão.
Na requisição o campo tipo não é enviado e a entrada não é salva no banco.

@lpirola, devo criar uma issue separada ou posso colocar no mesmo PR #1093?

**Comment by rolivegab** [comment]
Bug de não ter valor inicial para o campo type foi resolvido pelo mesmo PR

Resolved by #1093
