### ISSUE TITLE
Bug when logout and login without reload the page

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#879]
Pelo que pude perceber o problema é que o state da aplicação quando não recarrega a página continua com dados antigos, dando a impressão que está logado ainda com o usuário antigo.

**Comment by igr-santos** [comment]
Já identifiquei o problema, estou trabalhando na correção

**Comment by pedrotorres92** [comment]
Testado e aprovado. Não tem storie no Pivotal, por isso to aprovando por aqui. @lpirola @igr-santos
