### ISSUE TITLE
Feature MatchWidget component

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde#97]
## Introduction

Funcionalidade de combinação de opções e compartilhamento de conteúdo no Facebook.
## W.I.P.
- [x] Empty List (arraste seu item abaixo deste)
- [x] Criar Widget para o usuário final, deve haver um hover para editar Widget caso esteja na interface de administração
- [x] Criar container para configurar MatchWidget na interface de administração
- [x] Adicionar componente na lista de opções de Widget ao adicionar Bloco
- [x] Receber e salvar dados das opções
- [x] Receber e salvar dados do resultado das combinações das opções

**Comment by igr-santos** [comment]
Criado `OverlayWidget` implementando comportamento de overlay-click para qualquer novo Widget  em 78b31d9c56c952006b94154b5b2666afb3fdb36b

**Comment by igr-santos** [comment]
Parte da task **Adicionar componente na lista de opções de Widget ao adicionar Bloco** foi executada, a parte faltante está relacionada em trazer as informações na API.

**Comment by gabrielrtakeda** [comment]
## Staging Phase Bug:

Imagem configurada para o resultado da combinação não é exibida ao alternar entre as abas da tela de configuração do widget. Exibida somente logo em seguida ao upload ou após recarregar a página.

## Passo a passo para reprodução do bug.
- Adicionar as opções
- Clicar no botão “Salvar e Combinar”
- Inserir uma imagem
- Clicar na aba “Opções de combinação”
- E voltar para a aba “Resultados das combinações” `->` !! Note, a imagem configurada anteriormente não é exibida.
- Reload na página de “Resultados das combinações”
- Voilá, a imagem é carregada.

Provavelmente, a lista `match_list` no `widget` que fica no state não está sendo atualizada.

**Comment by igr-santos** [comment]
**Bug:** Ao pressionar `Salvar e Combinar` com input `Título do bloco de combinações` vazio, o redirecionamento não funciona, e não apresenta mensagem de erro, informando ser obrigatório

**Comment by igr-santos** [comment]
3fea154f2d5e0096acb88a69c20874faa101a807 Fix reload na página de resultados
