### ISSUE TITLE
[Webviewer/Mobrender] Posicionamento de blocos

### ISSUE THREAD

**Issue by igr-santos** [nossas/bonde#997]
Issue destinada a implementação de uma ordenação de blocos coerente.

## O problema

Dentro da atual edição de mobilização, existe uma funcionalidade que realiza o reposicionamento dos blocos de conteúdo, sendo possível mover blocos para cima e para baixo.

A implementação de bloco tem como visão o contexto do bloco e não de uma mobilização, ou seja, todos os blocos. Fazendo uma análise eu percebi que para realizar a movimentação do bloco, é necessário conhecimento de toda a lista de blocos.

## Conclusão

Como em uma lista duplamente encadeada, o bloco precisa conhecer o seu anterior e próximo bloco, quando um bloco move para cima, ele deve trocar o indice (posicionamento) com o bloco anterior, e quando um bloco move para baixo, ele deve trocar o indice com o próximo bloco.

Para atender essa demanda é preciso refatorar parte do código no `bonde-client/admin` e criar um metódo na api com a possibilidade de atualização de blocos em lista. Dessa forma o front passa a atualizar 2 blocos a cada movimento de bloco.

**Comment by lpirola** [comment]
@igr-santos se o endpoint atual, salva no banco de dados o position q vc passa como parâmetro, não seria possível disparar a mesma chamada atual para o bloco anterior, atualizando o position?

**Comment by igr-santos** [comment]
@lpirola a forma como implementamos essa funcionalidade dificulta bastante essa interação para uma requisição em cadeia, além de não garantir que as 2 ações vão ser executadas com sucesso, pode acabar ocorrendo um problema em uma das atualizações e não teríamos como fazer rollback, minha intenção é amarrar todas as pontas em relação a essa funcionalidade por ela já está a bastante tempo com problema. Com minha experiência em desenvolvimento backend, acredito que é mais fácil agir no backend pois esse tipo de atualização em lista é algo comum em APIs, mas quero ouvir um pouco do @hudsama para me certificar disso no Rails.

**Comment by hudsilva** [comment]
@igr-santos @lpirola visto a forma que o model `blocks` faz um `set_position` caso nao tenha um position definida e um método para alterar a posição. Nós vamos ter que atualizar esses comportamentos, quando passarmos a receber uma lista, pois ela já vira com as posições corretas, não sendo necessário o back ter que atualizar as posições novamente, correto @igr-santos?
Receber a lista seria tranquilo, pois poderiamos iterar sobre ela e ir atualizando os blocos passados. Gosto mais da primeira solução.

Outro ponto é que fazer a chamada do endpoint na v1 duas vezes não resolve (no atual estado) pois o próprio backend vai fazer o `switch_position` mudando a ordem correta, fazendo a segunda chamada passar uma position que sera modificada, não mantendo uma ordem que de fato deveria.

**Comment by igr-santos** [comment]
@hudsama é exatamente isso que precisamos fazer, eliminar a responsabilidade do backend de fazer o posicionamento (algo que faz mais sentido no lado do cliente), e habilitar a opção de atualização em uma lista de blocos, fazendo as mesma validações da atualização de um bloco, porem recebendo uma lista ao invés de um único objeto. O ideal é que a atualização de um bloco ainda funcione, mas caso isso dificulte a implementação, podemos atualizar os métodos que fazem atualização do bloco para passar o parametro como uma lista, é bem simples isso no cliente.

**Comment by hudsilva** [comment]
Gosto.
Sobre a atualização do blocos nós poderíamos fazer de duas forma
> manter o `update` normal e criar um novo método para atualizar em lista
> atualizar o `update` para verificar se foi enviado um único objeto ou uma lista e realizar suas devidas ações
> fazer o `update` receber uma lista sempre

Eu particularmente gosto mais do terceiro. De sempre receber uma lista, seja com um ou N blocos, definir meio que um `padrãozinho` nos params.
Como vc comentou que é tranquilo fazer isso no cliente, gostaria de seguir nesse lógica o/

**Comment by igr-santos** [comment]
@hudsama o problema do terceiro é que para atualizar um bloco, o padrão de API Rest é `PUT /blocks/id` para atualizar multiplos blocos o padrão da url deve ser um `PUT /blocks`, acho que o primeiro caso vai fazer mais sentido, em relação a mantermos padrão.

ref. https://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#restful

**Comment by lpirola** [comment]
@hudsama vou criar uma estória para adicionar o endpoint que aceita uma lista com o id o e position. Qual seria o formato ideal do json para enviar como parâmetro @igr-santos ?

**Comment by hudsilva** [comment]
@igr-santos de fato. Vamos criar um `PUT /blocks` que receba a lista, e mantemos o `PUT /blocks/:id` da mesma forma, já aproveitamos e atualizamos para remover a lógica de atualizar as `positions`

**Comment by lpirola** [comment]
@hudsama https://github.com/nossas/bonde-server/pull/494 comecei a fazer a remoção nesse PR

**Comment by hudsilva** [comment]
@lpirola minha ideia era usar ele mesmo, para fazer essa parte o backend :)

**Comment by igr-santos** [comment]
@lpirola @hudsama o formato ideal é o padrão, receber uma lista de objetos `Block` e atualizar conforme atributos enviados, sendo id um atributo obrigatório.

**Comment by igr-santos** [comment]
Resolução https://github.com/nossas/bonde-server/pull/494

Alterações necessárias no cliente:

- [x] Adicionar posicionamento ao novo bloco criado
- [x] Alterar lógica de update para posicionamento de blocos
